quantumlib/Stim

glue/cirq/stimcirq/_stim_sampler_test.py, src/circuit/circuit.cc, src/circuit/circuit.test.cc, src/simulators/detection_simulator.cc, src/simulators/detection_simulator.test.cc, src/simulators/frame_simulator.cc, src/simulators/frame_simulator.h, src/simulators/frame_simulator.test.cc, src/simulators/tableau_simulator.cc, src/simulators/tableau_simulator.test.cc
- TableauSimulator had X_ERROR and Z_ERROR implementations reversed
- Added unit tests comparing black box stats of all noisy tableau simulator methods to known-good stats from cirq
- Switched to saturating arithmetic when computing circuit counts, so that absurd rep counts don't avoid streaming optimizations [they just never finish since they have more than 2^64 results]
- Fix detection streaming not clearing the buffer that results were being written to, producing garbage data
- Add DebugForceResultStreamingRaii class for forcing streaming for smaller cases
- Add unit tests exercising streaming cases for frame simulator and detector simulator
=> Fix detection streaming and X/Z error swap

.github/workflows/ci.yml, src/simulators/tableau_simulator.pybind.cc
- Add test command to cibuildwheel configuration
- Fix unescaped unspecified encoding unicode characters in a docstring
- Drop pypy wheels from cibuildwheel tests
=> Fix stim.TableauSimulator.measure not resizing if needed for target

src/stabilizers/pauli_string.pybind.cc
Fixes https://github.com/quantumlib/Stim/issues/20
=> Escape unicode characters in utf8 doc string

glue/cirq/setup.py, setup.py, src/circuit/circuit_pybind_test.py, src/py/base.pybind.h, src/simulators/tableau_simulator.pybind.cc, src/stabilizers/pauli_string.pybind.cc, src/stabilizers/pauli_string.pybind.h, src/stabilizers/pauli_string_pybind_test.py, src/stabilizers/tableau.pybind.cc, src/stabilizers/tableau_pybind_test.py
- Refactor pauli string pybind code to split class method definitions over multiple statements
- Add support for proper `__imul__`
- Deprecate stim.PauliString.extended_product
- Refactor stim.PauliString.sign to return a complex value
=> Add support for imaginary phase to stim.PauliString python binding

.gitignore, dev/README.md, glue/cirq/setup.py, glue/cirq/stimcirq/__init__.py, glue/cirq/stimcirq/_circuit_conversion.py, glue/cirq/stimcirq/_circuit_conversion_test.py, glue/cirq/stimcirq/_stim_sampler.py, glue/python/generate_api_reference.py, setup.py, src/circuit/circuit.pybind.cc, src/circuit/circuit_pybind_test.py, src/py/base.pybind.cc, src/py/base.pybind.h, src/py/compiled_detector_sampler.pybind.cc, src/py/compiled_measurement_sampler.pybind.cc, src/py/stim.pybind.cc, src/simulators/tableau_simulator.pybind.cc, src/stabilizers/pauli_string.pybind.cc, src/stabilizers/pauli_string.pybind.h, src/stabilizers/pauli_string_pybind_test.py, src/stabilizers/tableau.pybind.cc, src/stabilizers/tableau_pybind_test.py
- Add `stimcirq.stim_circuit_to_cirq_circuit`
- Add sorta-hacky `stim.Circuit.flattened_operations` to make it possible
- Fix stimcirq doctest not running on imported methods/types
- Fix docstrings generated via pybind11 being over-indented
- Remove hashability of `stim.PauliString` and `stim.Tableau` (because they are mutable), and test that it's not re-added
=> Add `stimcirq.stim_circuit_to_cirq_circuit ` and polish bindings

src/circuit/circuit.pybind.cc, src/circuit/circuit_pybind_test.py, src/simd/simd_bits.cc, src/simd/simd_bits.h, src/simd/simd_bits.test.cc, src/simd/simd_bits_range_ref.cc, src/simd/simd_bits_range_ref.h, src/simd/simd_bits_range_ref.test.cc, src/simulators/tableau_simulator.cc, src/simulators/tableau_simulator.h, src/simulators/tableau_simulator.pybind.cc, src/simulators/tableau_simulator.test.cc, src/simulators/tableau_simulator_pybind_test.py, src/stabilizers/pauli_string.pybind.cc, src/stabilizers/pauli_string_pybind_test.py, src/stabilizers/tableau.pybind.cc, src/stabilizers/tableau.test.cc, src/stabilizers/tableau_pybind_test.py, src/stabilizers/tableau_transposed_raii.cc, src/stabilizers/tableau_transposed_raii.h
Translating ZX graphs into circuits requires the ability to translate post-selection into measurement. The new method `measure_kickback` allows this to be done by returning a kickback operation that can be used to cleanly invert random measurements. Testing this functionality from the python side then required increased ability to edit the simulator state.
- Add stim.TableauSimulator.do(stim.PauliString)
- Add TableauSimulator::paulis(PauliString)
- Add stim.TableauSimulator.set_num_qubits
- Add TableauSimulator::collapse_isolate_qubit
- Add TableauSimulator::set_num_qubits
- Add simd_bits::truncated_overwrite_from
- Refactor TableauSimulator::collapse to take ConstPointerRange<uint32_t>
- Add stim.TableauSimulator.measure_kickback
- Refactor TableauSimulator::collapse_qubit to return the …
=> Add various utility methods motivated by supporting ZX graph translation

CMakeLists.txt, src/simulators/measure_record_writer.h, src/simulators/tableau_simulator.cc, src/stabilizers/tableau.cc
- Give MeasureRecordWriter a virtual destructor (because it is deleted through std::unique_ptr pointers to its child types)
- Remove some std::move calls preventing possible copy elision
- Remove -Werror because it's brittle across time and space
Fixes https://github.com/quantumlib/Stim/issues/27
=> Fix some system-specific build errors

.github/workflows/ci.yml, src/stabilizers/pauli_string.cc, src/stabilizers/pauli_string.h, src/stabilizers/pauli_string.pybind.cc, src/stabilizers/pauli_string.pybind.h, src/stabilizers/pauli_string.test.cc, src/stabilizers/pauli_string_pybind_test.py, src/stabilizers/pauli_string_ref.cc
- Add `PauliString::ensure_num_qubits`
- Add `stim.PauliString.__add__` and `stim.PauliString.__iadd__` for concatenating / tensor product
- Extend `stim.PauliString.__mul__` to handle tensor powers (concatenation)
- Extend `stim.PauliString.__mul__` to allow different sized Paulis
- Extend `stim.PauliString.commutes` to allow different sized Paulis
- Extend `PauliString.__init__` to take Sequence[int]
- Extend `PauliString.__init__` to take stim.PauliString
=> Extend arithmetic operators (tensor products, differing lengths)

src/simulators/tableau_simulator.cc, src/simulators/tableau_simulator.h, src/simulators/tableau_simulator.pybind.cc, src/simulators/tableau_simulator.test.cc, src/simulators/tableau_simulator_pybind_test.py, src/stabilizers/tableau.test.cc, src/stabilizers/tableau_transposed_raii.cc, src/stabilizers/tableau_transposed_raii.h
- Fix `TableauSimulator::collapse_isolate_qubit` using H_XY instead of S (H_XY is unsafe here because not a no-op on the zero state).
- Add several tests that would have detected this bug
- Add `TableauSimulator::append_S`
- Improve `stim.TableauSimulator.measure_kickback` so it isolates qubits so their Z term is not spuriously added to later kickbacks
- Add `stim.TableauSimulator.canonical_stabilizers`
=> Add (and fix bugs revealed by) stim.TableauSimulator.canonical_stabilizers

CMakeLists.txt, README.md, src/circuit/circuit.cc, src/circuit/gate_data.cc, src/circuit/gate_data.h, src/gate_help.cc, src/gate_help.h, src/main_helper.cc, src/simulators/error_fuser.h, src/simulators/error_fuser.test.cc
- `--help` can now be given `gates` (lists all gates) or a gate name (describes the gate)
- Added code to autogenerate the supported gates content in the README, using the --help output
- Fix circuit parsing inverted targets for gates that don't support them
- Modify Gate to have an ExtraGateData function for doc and test data
- Remove TruncatedArray (use FixedCapVector instead)
- Increase max error components to 16 in add_error_combinations (so error analysis on generated color code succeeds)
- Better error message for too-complex errors
=> Add --help gate support

README.md, src/arg_parse.cc, src/arg_parse.h, src/arg_parse.test.cc, src/circuit/gate_data.cc, src/gate_help.cc, src/gen/circuit_gen_main.cc, src/gen/circuit_gen_main.h, src/main_helper.cc, src/main_helper.test.cc, src/simulators/error_fuser.cc, src/simulators/error_fuser.h, src/simulators/error_fuser.perf.cc, src/simulators/error_fuser.test.cc, src/test_util.test.cc, src/test_util.test.h
- Add `--allow_gauge_detectors` option to `--analyze_errors` mode 
- Deprecate `--detector_hypergraph` for `--analyze_errors`
- Split main helper into several mode helper main methods
- Add `find_open_file_argument`
- Refactor `find_enum_argument` to use a `std::map`
- Adding testing util `RaiiTempNamedFile`
- Make ErrorFuser check for non-Z basis dependence at start of circuit when validating detectors
- Add `validate_detectors` field to ErrorFuser
- When `validate_detectors` is true, add 50% errors instead of raising exceptions for gauge detectors
- Inline a few flag constants
- Fix measurement help only listing 1 stabilizer generator instead of 2
- Fix `--help` going to std::cerr instead of std::cout
- Fix help commands being case sensitive
=> Add support for gauge detectors to `--analyze_errors` mode

glue/javascript/pauli_string.js.cc, src/stabilizers/pauli_string.h, src/stabilizers/pauli_string.pybind.cc, src/stabilizers/pauli_string.pybind.h, src/stabilizers/pauli_string.test.cc, src/stabilizers/pauli_string_pybind_test.py, src/stabilizers/tableau.cc, src/stabilizers/tableau.h, src/stabilizers/tableau.pybind.cc, src/stabilizers/tableau.test.cc, src/stabilizers/tableau_pybind_test.py
- Add `stim.Tableau.inverse(*, unsigned=False)`
- Add `stim.Tableau.{x,y,z}_output_pauli(input_index, output_index)`
- Add `stim.Tableau.inverse_{x,y,z}_output_pauli(input_index, output_index)`
- Add `stim.Tableau.inverse_{x,y,z}_output(input_index, *, unsigned=False)`
- Add `stim.PauliString.__{i,}truediv__`
- Add `stim_internal::pauli_xz_to_xyz` helper method
Fixes https://github.com/quantumlib/Stim/issues/50
=> Add several query methods to Tableau

CMakeLists.txt, README.md, src/arg_parse.cc, src/arg_parse.h, src/circuit/circuit.cc, src/circuit/circuit.h, src/circuit/gate_data_hada.cc, src/dem/detector_error_model.cc, src/dem/detector_error_model.h, src/dem/detector_error_model.test.cc, src/gen/circuit_gen_main.cc, src/main_helper.cc, src/main_helper.test.cc, src/simd/pointer_range.h, src/simulators/error_fuser.cc, src/simulators/error_fuser.h, src/simulators/error_fuser.test.cc
- Add stim::DetectorErrorModel
- Add stim_internal::{DemInstructionType,RelValue,DemRelativeSymptom,DemInstruction}
- Add stim_internal::ConstPointerRange::{front,back}
- Move several circuit parsing methods up to circuit.h for re-use
- Fix circuit move constructor/assignment copying target data instead of moving it
- Bit worried about the Chesterton fence aspect of removing this. I think I originally added it because it was necessary, but I think that was when the target data was accessed using a vector pointer plus offset instead of just a pointer range. It was the vector pointer that was going stale, so now it *should* be safe to move...
- Fix Hadamard gate help redundantly saying the bloch rotation
- Add stim_internal::{ostream_else_cout,find_output_stream_argument} and use it in …
=> Define classes for storing detector error models

glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_stim_to_cirq_test.py, src/circuit/circuit.cc, src/circuit/circuit.h, src/circuit/circuit.test.cc, src/circuit/gate_data.h, src/circuit/gate_data_annotations.cc, src/dem/detector_error_model.cc, src/dem/detector_error_model.h, src/dem/detector_error_model.test.cc
- Fix negative coordinates creating parse failures in stim Circuit repr
- Fix int coordinates degrading to floats when round tripping
- Add DetectorErrorModel::from_file methods
- Fix OBSERVABLE_INCLUDE argument not being validated to be a non-negative integer
Fixes https://github.com/quantumlib/Stim/issues/93
Fixes https://github.com/quantumlib/Stim/issues/81
Fixes https://github.com/quantumlib/Stim/issues/70
=> Polish stimcirq coordinate preservation

src/circuit/circuit.cc, src/circuit/circuit.h, src/dem/detector_error_model.cc, src/dem/detector_error_model.h, src/simd/pointer_range.h, src/simd/simd_bits_range_ref.cc, src/simd/simd_bits_range_ref.h, src/simd/simd_compat.test.cc, src/simd/simd_util.test.cc, src/simd/sparse_xor_vec.h, src/simulators/error_analyzer.test.cc, src/simulators/vector_simulator.cc, src/simulators/vector_simulator.h, src/stabilizers/pauli_string.cc, src/stabilizers/pauli_string.h, src/stabilizers/pauli_string_ref.cc, src/stabilizers/pauli_string_ref.h, src/stabilizers/tableau.cc, src/stabilizers/tableau.h, src/str_util.h
- The operator<< overloads can be moved inside the stim namespace? Was it gtest forcing me to put them outside it all along?
Fixes https://github.com/quantumlib/Stim/issues/86
=> Fix incompatibility with gtest 1.11

doc/python_api_reference_vDev.md, glue/cirq/stimcirq/_cirq_to_stim.py, src/circuit/circuit.cc, src/circuit/circuit.h, src/circuit/circuit.pybind.cc, src/circuit/circuit.test.cc, src/circuit/circuit_pybind_test.py, src/circuit/circuit_repeat_block.pybind.cc, src/dem/detector_error_model.cc, src/dem/detector_error_model.h, src/dem/detector_error_model.pybind.cc, src/dem/detector_error_model.test.cc, src/dem/detector_error_model_pybind_test.py, src/dem/detector_error_model_repeat_block.pybind.cc, src/py/base.pybind.cc, src/py/base.pybind.h, src/stabilizers/pauli_string.cc, src/stabilizers/pauli_string.h, src/stabilizers/pauli_string.pybind.cc, src/stabilizers/pauli_string.test.cc
- Fix `stim.Circuit.__repr__` not indenting instructions
- Fix `stim.DetectorErrorModel.__repr__` not indenting instructions
- Add `stim.Circuit.__getitem__` slicing
- Add `stim.DetectorErrorModel.__getitem__` slicing
- Fix `stim.PauliString.__getitem__` having doubled documentation
- Fix `stim.PauliString.__setitem__` having doubled documentation
- Add Circuit::py_get_slice, DetectorErrorModel::py_get_slice, PauliString::py_get_slice
- Add pybind normalize_index_or_slice utility for `__getitem__` methods
Fixes https://github.com/quantumlib/Stim/issues/92
=> Add circuit and detector error model slicing

CMakeLists.txt, doc/usage_command_line.md, src/main_helper.test.cc, src/simd/fixed_cap_vector.h, src/simd/fixed_cap_vector.test.cc, src/simulators/error_analyzer.cc, src/simulators/error_analyzer.h, src/simulators/error_analyzer.test.cc, src/simulators/frame_simulator.cc, src/test_util.test.h
- Add str/clear/<< to FixedCapVector
- Fix FixedCapVector::operator< always returning true
- Move decompose
- Add ErrorAnalyzer::do_global_error_decomposition_pass
- Make do_global_error_decomposition_pass verify all errors are decomposed
- Move ErrorAnalyzer::add_error_combinations body into .cc file
- Extract ErrorAnalyzer::decompose_helper_add_error_combinations
Fixes https://github.com/quantumlib/Stim/issues/106
Fixes https://github.com/quantumlib/Stim/issues/103
=> Add a fallback  error analysis decomposition strategy that uses other errors

doc/python_api_reference_vDev.md, src/circuit/circuit.cc, src/circuit/circuit.pybind.cc, src/circuit/circuit.test.cc, src/circuit/circuit_instruction.pybind.cc, src/circuit/circuit_instruction.pybind.h, src/circuit/circuit_instruction_pybind_test.py, src/circuit/circuit_pybind_test.py, src/circuit/circuit_repeat_block.pybind.cc, src/circuit/circuit_repeat_block.pybind.h, src/circuit/circuit_repeat_block_test.py, src/py/base.pybind.cc, src/py/base.pybind.h, src/py/compiled_detector_sampler.pybind.cc, src/py/compiled_detector_sampler.pybind.h, src/py/compiled_detector_sampler_pybind_test.py, src/py/compiled_measurement_sampler.pybind.cc, src/py/compiled_measurement_sampler.pybind.h, src/py/compiled_measurement_sampler_pybind_test.py
Adds some missing repetition count validation.
Fixes https://github.com/quantumlib/Stim/issues/118
Fixes https://github.com/quantumlib/Stim/issues/124
=> Add sample_write methods to compiled samplers

glue/cirq/setup.py
- cirq is now a meta-package that pulls in all cirq
packages including cirq-google, cirq-ionq, cirq-rigetti, etc.
- Change dependency to cirq-core to only pull in necessary components.
=> Fix dependency on cirq

CMakeLists.txt, src/io/measure_record_reader.cc, src/io/measure_record_reader.h, src/io/measure_record_reader.test.cc, src/io/measure_record_writer.h
The API is simple, but supports rather varied file formats (one vs many measure records per file, known vs unknown record length) in a consistent way.
Tests fall into three groups: counterparts to tests for writers, write-read-compare tests and additional tests for multi-record file formats.
Follow-ups:
* benchmarking tests for the readers,
* integration with `MeasureRecord`,
* support for PTB64 file format,
* read counterpart to `write_table_data`,
* possible refactoring of `write_table_data` to fit it into `MeasureRecordWriters` and similar for the read side (contingent on a fix for the performance regression this is causing).
=> Basic readers

src/stim/circuit/circuit_instruction.pybind.h, src/stim/io/measure_record_reader.cc, src/stim/io/measure_record_reader.h, src/stim/io/measure_record_reader.test.cc, src/stim/io/measure_record_writer.cc, src/stim/io/measure_record_writer.h, src/stim/io/measure_record_writer.test.cc
- Add MeasureRecordWriter::write_bits
- Add MeasureRecordReader::read_records_into
- Fix MeasureRecordReaderFormat{R8,B8}::next_record not reading to end of current record, and also unconditionally reporting failure
- Combine `MeasureRecordReaderFormatR8::{run_length,generated}_{0s,1s}` into `buffered_{0s,1s}`
- Fix MeasureRecordReaderFormatR8 not explicitly checking for and tracking the terminal 1 bit
- Rename `read_bytes` to `read_bits_into_bytes`
=> Add support for bulk reading of measurement data

.github/workflows/ci.yml, doc/python_api_reference_vDev.md, doc/usage_command_line.md, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/help.cc, src/stim/main_namespaced.cc, src/stim/main_namespaced.test.cc, src/stim/py/base.pybind.cc, src/stim/py/base.pybind.h, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.h, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.h, src/stim/py/stim.pybind.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/tableau.pybind.cc
- Refactor PYBIND_SHARED_RNG to take an object argument that determines whether system entropy or manual seeding is used
- Add keyworkd-only seed argument to stim.Circuit.compile{_detector}_sampler()
- Add keyworkd-only seed argument to constructors of stim.CompiledCircuit{Detector}Sampler
- Add `--seed` option to `stim sample` and `stim detect` command line modes
Fixes https://github.com/quantumlib/Stim/issues/143
=> Add the ability to seed samplers when creating them

src/stim/io/measure_record_reader.cc, src/stim/io/measure_record_reader.test.cc
- Fix MeasureRecordReader refusing to read detection event data unless it's in DETS format
- Fix b8 read_bits_into_bytes not being aggressive enough with getting to end of record from the start
=> Fix issues with bulk reading using MeasureRecordReader

CMakeLists.txt, src/stim/io/measure_record_reader.cc, src/stim/io/measure_record_reader.h, src/stim/io/measure_record_reader.perf.cc, src/stim/io/measure_record_reader.test.cc, src/stim/io/sparse_shot.cc, src/stim/io/sparse_shot.h, src/stim/io/sparse_shot.test.cc, src/stim/main_namespaced.cc, src/stim/main_namespaced.test.cc, src/stim/mem/simd_bit_table.cc, src/stim/mem/simd_bits.cc, src/stim/mem/simd_bits.h, src/stim/mem/simd_bits.test.cc, src/stim/mem/simd_bits_range_ref.h, src/stim/mem/simd_bits_range_ref.test.cc
- Add a dense (into bit packed memory) and sparse (into vector of hits) variants
- Add SparseShot struct for reading sparse data
- Fix various readers not knowing about the expected layout of data they were reading
- Add benchmarks for read performance
- Add deprecation warning to `--prepend_observables`
- Add prefix_ref method to simd_bits
- Move simd-bit-sizing methods into stim:: namespace
```
[....................*....................]  80 us (vs  80 us) (120 MBits/s) read_01_dense_per10
[....................*....................]  51 us (vs  57 us) ( 19 MPops/s) read_01_sparse_per10
[....................*....................] 5.0 us (vs 5.6 us) (1.9 GBits/s) read_b8_dense_per10
[....................*....................] 7.8 us (vs 8.0 us) (120 MPops/s) read_b8_sparse_per10 …
```
=> Add better-performance read-entire-record methods

.github/workflows/ci.yml, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.test.cc, src/stim/probability_util.cc
- Also improve the error message that comes out of the rare sampler when a bad probability goes into it
- Also work around a weird build breakage in Pillow dependency from cirq-core
=> Fix stim::Circuit::validate_gate not detecting NaN probabilities

doc/python_api_reference_vDev.md, glue/python/generate_api_reference.py, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/dem/detector_error_model.cc, src/stim/dem/detector_error_model.h, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model.test.cc, src/stim/dem/detector_error_model_pybind_test.py, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/dem/detector_error_model_target_pybind_test.py, src/stim/simulators/measurements_to_detection_events.h, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/pauli_string.pybind.h, src/stim/stabilizers/pauli_string_pybind_test.py, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_pybind_test.py
- Add `stim.DetectorErrorModel.num_errors`
- Add `stim.{Circuit,DetectorErrorModel}.approx_equals`
- Add `*,+,*=,+=` to `stim.DetectorErrorModel`
- Add `stim.DetectorErrorModel.append`
- Add static factory methods to `stim.DemTarget`
- Make `stim.{Circuit,PauliString,Tableau,DetectorErrorModel}` pickleable
Fixes https://github.com/quantumlib/Stim/issues/116
Fixes https://github.com/quantumlib/Stim/issues/160
Fixes https://github.com/quantumlib/Stim/issues/161
Fixes https://github.com/quantumlib/Stim/issues/162
Fixes https://github.com/quantumlib/Stim/issues/163
=> Squash five issues

.github/workflows/ci.yml, CMakeLists.txt, doc/python_api_reference_vDev.md, setup.py, src/stim.h, src/stim/dem/detector_error_model.cc, src/stim/dem/detector_error_model.h, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model.test.cc, src/stim/dem/detector_error_model_pybind_test.py, src/stim/io/measure_record_reader.cc, src/stim/io/measure_record_reader.h, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/min_distance.cc, src/stim/simulators/min_distance.h, src/stim/simulators/min_distance.perf.cc, src/stim/simulators/min_distance.test.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc
Performs a breadth first search over the graph defined by a graphlike error model, searching for the smallest set of errors that has no symptoms but does cause a logical error.
The actual graph being searched over is implicit. The nodes of the implicit graph have one or two detection events and a set of logical observable frame changes. The neighbors of a node are defined to be the states that can be reached by applying any error that touches the **single marked symptom that is allowed move**, producing tweaked symptoms and frame changes. The initial nodes that the search branches out from come from edges that actually cross an observable: the symptoms and frame changes of that edge define a starting node.
The reason for the restriction of neighbors to involve only one symptom at a time, …
=> Compute graphlike distance given an error model

src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.test.cc
- Error analyzer goes back to front, not front to back
=> Fix error analyzer iterating fused MPP operations in wrong order

src/stim/mem/simd_bits_range_ref.test.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.test.cc
- Within a non-qubit-overlapping subset there was already a reversal, so the new reversal was cancelling it instead of doing the right thing
- Maintain the reversal of qubit-overlapping subsets
=> Second fix to reversing MPP ordering in error analysis

.github/workflows/ci.yml, doc/file_format_stim_circuit.md, glue/cirq/setup.py, glue/python/create_sdists.sh, glue/python/generate_api_reference.py, glue/zx/setup.py, setup.py
- Fix help text in create_sdists.sh
- Add "-dev" option to generate_api_reference.py and force it in ci
- Run ci on tags
- Fixes a typo in the stim file format documentation
=> Bump dev version to 1.8.dev0

glue/python/src/stim/__init__.py, setup.py
- For sdist, fix specifying `data_files=` on each Extension instead of on the package itself
- For sdist, fix headers being given as `data_files=` instead of `headers=`
- For wheels, fix using the avx2 instead of the vanilla package to determine CPU capabilities
- It was touching avx instructions along the way, causing crashes on M1 macs
First part of fixing https://github.com/quantumlib/Stim/issues/179
=> Fix package installation issues

BUILD, WORKSPACE, doc/regen_docs_not_portable.sh, glue/cirq/stimcirq/_cirq_to_stim.py, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit.test.cc, src/stim/circuit/gate_data_annotations.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model.test.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/main_namespaced.test.cc, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/march.pybind.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.h, src/stim/simulators/error_analyzer.test.cc, src/stim/simulators/measurements_to_detection_events.h, src/stim/simulators/min_distance.cc, src/stim/simulators/min_distance.h, src/stim/simulators/min_distance.perf.cc, src/stim/simulators/min_distance.test.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/tableau.pybind.cc
- Give a proper circuit stack trace of the instruction location when error analysis fails:
- tick layer
- most-general-to-most-specific ordering
- error sensitivities of involved detectors/observables
- the specific qubit that was collapsing
- coordinate metadata of involved detectors and qubits
- Add `Circuit::count_ticks`
- Add `Circuit::get_final_qubit_coords`
- Add `Circuit::describe_instruction_location`
- Add `ErrorAnalyzer::TICK`
- Add `Circuit::final_coord_shift`
- Add `Circuit::coords_of_detector`
- Run autoformat
- Add `:stim_dev_wheel` bazel target for easier python testing during development
=> Improve error messages for anticommuting obs/dets *even more*

doc/result_formats.md, glue/cirq/stimcirq/__init__.py, glue/cirq/stimcirq/_cirq_to_stim.py, glue/cirq/stimcirq/_det_annotation.py, glue/cirq/stimcirq/_det_annotation_test.py, glue/cirq/stimcirq/_measure_and_or_reset_gate.py, glue/cirq/stimcirq/_measure_and_or_reset_gate_test.py, glue/cirq/stimcirq/_obs_annotation.py, glue/cirq/stimcirq/_obs_annotation_test.py, glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_stim_to_cirq_test.py, glue/cirq/stimcirq/_two_qubit_asymmetric_depolarize.py, glue/cirq/stimcirq/_two_qubit_asymmetric_depolarize_test.py, src/stim/circuit/circuit_gate_target.pybind.cc, src/stim/circuit/circuit_gate_target_pybind_test.py, src/stim/circuit/circuit_instruction.pybind.cc, src/stim/circuit/circuit_instruction.pybind.h, src/stim/circuit/circuit_instruction_pybind_test.py, src/stim/dem/detector_error_model_instruction.pybind.cc, src/stim/dem/detector_error_model_instruction_pybind_test.py, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/dem/detector_error_model_target_pybind_test.py, src/stim/help.cc, src/stim/io/stim_data_formats.cc
- Add support for converting MPP, DETECTOR, and OBSERVABLE_INCLUDE
- Add a json resolver for opt-in compatibility with cirq serialization
- Rewrite stim-to-cirq to use CircuitInstruction instead of the old flattened approach
- Move custom gates into their own files
- Refactor stim-to-cirq direction to use a CircuitTranslationTracker helper
- Substantially cleanup the stim-to-cirq handler dictionary
- Fix circuit/dem instructions and targets not being hashable
- Also, improve the result format documentation
=> Update stimcirq to handle more gates

glue/cirq/stimcirq/__init__.py, glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_stim_to_cirq_test.py, glue/cirq/stimcirq/_sweep_pauli.py, glue/cirq/stimcirq/_sweep_pauli_test.py, glue/cirq/stimcirq/_two_qubit_asymmetric_depolarize.py
- Add `stimcirq.SweepPauli` for representing the configuration-controlled gates
- Has a stim sweep bit index and a cirq sweep symbol, for cross compatibility
=> Add support for sweep targets to stimcirq

glue/cirq/stimcirq/__init__.py, glue/cirq/stimcirq/_cirq_to_stim.py, glue/cirq/stimcirq/_cirq_to_stim_test.py, glue/cirq/stimcirq/_det_annotation.py, glue/cirq/stimcirq/_det_annotation_test.py, glue/cirq/stimcirq/_measure_and_or_reset_gate.py, glue/cirq/stimcirq/_measure_and_or_reset_gate_test.py, glue/cirq/stimcirq/_obs_annotation.py, glue/cirq/stimcirq/_obs_annotation_test.py, glue/cirq/stimcirq/_shift_coords_annotation.py, glue/cirq/stimcirq/_shift_coords_annotation_test.py, glue/cirq/stimcirq/_stim_sampler.py, glue/cirq/stimcirq/_stim_sampler_test.py, glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_stim_to_cirq_test.py, glue/cirq/stimcirq/_sweep_pauli.py, glue/cirq/stimcirq/_sweep_pauli_test.py, glue/cirq/stimcirq/_two_qubit_asymmetric_depolarize.py, glue/cirq/stimcirq/_two_qubit_asymmetric_depolarize_test.py
- Add support for relative indices (as opposed to measurement keys) to Det and Obs annotations
- Add `stimcirq.ShiftCoordsAnnotation`
- Add some guard rails for measurement keys crossing loop boundaries
- Add `flatten` option to `stimcirq.stim_circuit_to_cirq_circuit`
- Add `MeasureAndOrResetGate._circuit_diagram_info_`
- Run an autoformatter on stimcirq
=> Add stimcirq support for converting `REPEAT` blocks into `cirq.CircuitOperation`s

doc/python_api_reference_vDev.md, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_gate_target.pybind.cc, src/stim/circuit/circuit_gate_target.pybind.h, src/stim/circuit/circuit_pybind_test.py
- Add `stim.Circuit.append` alias for `stim.Circuit.append_operation`
- Make it an error to pass 0 instead of 1 parens arguments into `stim.Circuit.append` (e.g. for X_ERROR gate)
- `stim.append_operation` has to allow this for backwards compatibility
- Allow single targets to be passed not in a list, e.g. `stim.append("H", 0)`
=> Make `stim.Circuit.append` more convenient

glue/cirq/stimcirq/_stim_sampler.py
The `cirq.Result` constructor is deprecated as of https://github.com/quantumlib/Cirq/pull/4806. Instead, we should use a concrete type like `cirq.ResultDict`. This changes `StimSampler` to use `cirq.ResultDict` when available, to avoid deprecation warnings.
I'm also curious to know what is the support policy for stimcirq supporting different pyle versions. This workaround can be removed whenever support for cirq < 0.14 is dropped.
=> Use cirq.ResultDict in StimSampler when available

src/stim/py/march.pybind.cc
Stim includes some C preprocessor logic which assists in looking up processor intrinsics for specialized / accelerated operator evaluation. Currently, the logic forks on x86 Windows / x86 not-Windows, which breaks on modern Apple devices with ARM64 processors. This PR adds basic support for these processors by adding an extra (dummy) clause to the preprocessor logic, but it does not supply any specialized support for ARM64 features.
This borrows from the ARM64 clause here: https://opensource.apple.com/source/WTF/WTF-7601.1.46.42/wtf/Platform.h.auto.html .
=> add preprocessor clauses for bare support for aarch64

glue/sample/setup.py, glue/sample/src/simmer/collection_work_manager.py, glue/sample/src/simmer/main.py, glue/sample/src/simmer/main_collect.py, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_gate_target.pybind.cc, src/stim/circuit/circuit_instruction.pybind.cc, src/stim/circuit/circuit_repeat_block.pybind.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model_instruction.pybind.cc, src/stim/dem/detector_error_model_repeat_block.pybind.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/py/base.pybind.cc, src/stim/py/base.pybind.h, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.h, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/stim.pybind.cc, src/stim/simulators/matched_error.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/tableau_simulator.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator.pybind.h, src/stim/simulators/vector_simulator.cc, src/stim/simulators/vector_simulator.h, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/tableau.pybind.cc
- Samplers created without a specified seed now always reseed from external entropy, instead of falling back to a shared rng
- This fixes an issue where forking the process multiple times and then sampling a circuit within each child processes would return identical samples, which could occur when using python multiprocessing
- Add stim_pybind namespace and use it in some files
- As a second layer of defense, simmer also now forces multiprocessing to create workers using "spawn" mode, which avoids forking memory
Fixes https://github.com/quantumlib/Stim/issues/207
=> Mitigate rng state duplication from multiprocessing forking state

glue/cirq/setup.py, glue/sample/README.md, glue/sample/setup.py, glue/sample/src/simmer/collection_tracker_for_single_task.py, glue/sample/src/simmer/collection_work_manager.py, glue/sample/src/simmer/main_collect.py, glue/sample/src/simmer/main_combine.py, glue/sample/src/simmer/main_plot.py, glue/sample/src/simmer/main_test.py, glue/sample/src/simmer/task.py, glue/zx/setup.py, setup.py
- Specify encoding when reading readme for long_description of python wheel
- Add `-metadata_func` option to `simmer collect`
- Make `-max_error` or `-max_shot` optional for `simmer collect`
- Fix already-done tasks not being counted as finished in `simmer collect` progress message
- Use `compile` on function expressions given by command line
- Make `simmer combine` read from stdin when given no arguments
- Add `-filter_func` argument to `-simmer_plot`
- Improve curve sort ordering to do numbers numerically instead of alphabetically
Fixes https://github.com/quantumlib/Stim/issues/214
Fixes https://github.com/quantumlib/Stim/issues/212
=> Simmer polish and implicit setup.py readme encoding fix

.github/workflows/ci.yml, doc/python_api_reference_vDev.md, glue/python/generate_api_reference.py, glue/python/src/stim/__init__.py, glue/sample/src/sinter/main_test.py, glue/sample/src/sinter/plotting.py, setup.py, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_gate_target.pybind.cc, src/stim/circuit/circuit_instruction.pybind.cc, src/stim/circuit/circuit_repeat_block.pybind.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model_instruction.pybind.cc, src/stim/dem/detector_error_model_repeat_block.pybind.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/march.pybind.cc, src/stim/py/stim.pybind.cc, src/stim/simulators/matched_error.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/tableau.pybind.cc
- Fix "stim.h not found" when pip installing sdist
- Split machine architecture detection (avx/sse/other) into a separate C++ python extension
- Split up cibuildwheel making wheels over more ci checks (based on python version)
- Remove `pybind11::module_local()` from class definitions now that two variants of stim are never imported in the same interpreter
- Shorten machine architecture package names
- Bump cibuildwheel version
- Fix an ordering issue when plotting for sinter
Fixes https://github.com/quantumlib/Stim/issues/225
=> Iterate on continuous integration and wheel building

glue/cirq/stimcirq/_measure_and_or_reset_gate.py, glue/cirq/stimcirq/_stim_sampler_test.py
SingleQubitGate was deprecated in https://github.com/quantumlib/Cirq/pull/5272 and is scheduled for removal. Remove usage of it by defining `_num_qubits_` explicitly to fix deprecation warnings when using stim with nightly cirq.
=> Remove usage of deprecated `cirq.SingleQubitGate`

.gitignore, doc/python_api_reference_vDev.md, doc/usage_command_line.md, src/stim.test.cc, src/stim/benchmark_util.perf.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/dem/detector_error_model.cc, src/stim/dem/detector_error_model.test.cc, src/stim/help.cc, src/stim/main_namespaced.cc, src/stim/mem/simd_bits_range_ref.h, src/stim/py/base.pybind.h, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.h, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/march.pybind.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.h, src/stim/simulators/error_analyzer.perf.cc, src/stim/simulators/error_analyzer.test.cc, src/stim/simulators/error_matcher.cc, src/stim/simulators/min_distance.perf.cc, src/stim/simulators/min_distance.test.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/vector_simulator.cc
- Add `block_decompose_from_introducing_remnant_edges` option
- Add `ignore_decomposition_failures` option
- Make decomposition do a much stronger brute force search to avoid introducing remnant edges unless needed
- Autoformat
- Add `.cmake` directory to .gitignore
- BREAKING CHANGE: changed default value of `stim.Circuit.shortest_graphlike_error:ignore_ungraphlike_errors` from False to True
Fixes https://github.com/quantumlib/Stim/issues/202
=> Improve error decomposition

.gitignore, WORKSPACE, glue/python/src/stim/__init__.py, glue/sample/src/sinter/__init__.py, glue/sample/src/sinter/collection_test.py, glue/sample/src/sinter/collection_tracker_for_single_task.py, glue/sample/src/sinter/collection_work_manager.py, glue/sample/src/sinter/decoding_internal.py, glue/sample/src/sinter/executable_task.py, glue/sample/src/sinter/existing_data.py, glue/sample/src/sinter/main_plot.py, glue/sample/src/sinter/plotting.py, glue/sample/src/sinter/probability_util.py, glue/sample/src/sinter/probability_util_test.py, glue/sample/src/sinter/task_stats.py
- Bump googletest version in Bazel workspace
- Add workaround for pytest+pycharm+pybind working together to fail at making `assert circuit1 == circuit2` print a useful failure message
- Expose better_sorted_strm_terms, binomial_relative_likelihood_range, TaskSummary, AnonTaskStats from sinter
- Add a second 'desperate=True' pass for assigning work
- Don't plot points at negative infinity in log error rate plots
- Added methods for looking at what defines the strong_id
=> Iterate on sinter work assignment

glue/sample/README.md, glue/sample/src/sinter/__init__.py, glue/sample/src/sinter/collection_tracker_for_single_task.py, glue/sample/src/sinter/decoding.py, glue/sample/src/sinter/executable_task.py, glue/sample/src/sinter/existing_data.py, glue/sample/src/sinter/main_plot.py, glue/sample/src/sinter/plotting.py, glue/sample/src/sinter/plotting_test.py, glue/sample/src/sinter/task.py
- Refactor `sinter.plot_error_rate` and `sinter.plot_discard_rate` to make them more flexible
- Stop setting properties like the title, ylim, loglog to avoid interfering with what caller wants.
- Remove sinter.DataPointId; split x_func argument out of curve_func argument
- Replace sinter.CurveStats with sinter.group_by
- Increase default max batch seconds from 30s to 120s
- Rename `to_case_executable` to `to_executable_task`
- Add more safety checks around the poststelection mask
- Fix postselection mask size inconsistently including observables or not
- Add `sinter.Task.strong_id` convenience method
=> Iterate on sinter's design

glue/sample/requirements.txt, glue/sample/src/sinter/decoding_pymatching.py, glue/sample/src/sinter/decoding_test.py
- pymatching no longer requires the input to have just one connected component
- Use new 'fault_ids' instead of old 'qubit_id' on edges
- Add a test that invincible observables work correctly
- Loosen sinter's declared requirements
=> Stop adding dummy edges to ensure one connected component for pymatching

.github/workflows/ci.yml, doc/developer_documentation.md, doc/python_api_reference_vDev.md, glue/python/src/stim/_main_argv.py, setup.py, src/stim/circuit/gate_target.cc, src/stim/circuit/gate_target.test.cc, src/stim/py/stim.pybind.cc, src/stim/py/stim_pybind_test.py, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc
- Add `stim.main` for acting like command line from python
- Add `stim` entrypoint to stim's setup.py
- Fix some documentation typos
- Refactor target methods like `target_x` to return a `stim.GateTarget` instead of a raw integer
=> Install `stim` command line tool when pip installing stim

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, glue/sample/README.md, glue/sample/src/sinter/main_plot.py, glue/sample/src/sinter/plotting.py, glue/sample/src/sinter/plotting_test.py, src/stim/circuit/circuit.pybind.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/dem/detector_error_model_target.pybind.h, src/stim/io/read_write.pybind.cc, src/stim/io/read_write.pybind.h, src/stim/io/read_write_pytest.py, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/stim.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.h, src/stim/simulators/measurements_to_detection_events_test.py
- Add `bit_pack_result=false` argument to m2d convert method
- Extract `stim_pybind::transposed_simd_bit_table_to_numpy` method
- Extract `stim_pybind::numpy_array_to_transposed_simd_table` method
- Fix a few compiler warnings
- Rename curve_func parameter to group_func in sinter to be consistent with command line tool
=> Add optional bit packing when converting measurements to detection events

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/main_namespaced.cc, src/stim/simulators/measurements_to_detection_events.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.h, src/stim/simulators/measurements_to_detection_events_test.py
- Fix an m2d segfault caused by `convert_file` not using the noiseless variant of a circuit (and triggering a safety check)
- Fix a nasty m2d conversion bug where observables were only keeping their last included component. **This circuit was failing:**
```
MX 0
OBSERVABLE_INCLUDE(0) rec[-1]
MX 0
OBSERVABLE_INCLUDE(0) rec[-1]
```
=> Add `separate_observables=False` argument to measurement-to-detections conversion

glue/sample/src/sinter/collection_tracker_for_single_task.py, glue/sample/src/sinter/collection_work_manager.py, glue/sample/src/sinter/main_collect.py, glue/sample/src/sinter/printer.py
- Fix showing shots left before knowing how many were collected
- Fix redundant status message after keyboardinterrupt
- Switch from any amount of waiting to just immediate SIGKILL-ing of children when shutting down workers
=> Show 'initializing...' when waiting for strong id in sinter

glue/cirq/stimcirq/_shift_coords_annotation_test.py, glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_stim_to_cirq_test.py
- Also maintain compat with current version
- Avoid measure key == qubit name due to circuit diagram change
- Avoid implicit measure key from cirq.measure due to change in the default
- Start using `use_repetition_ids`
Fixes https://github.com/quantumlib/Stim/issues/224
=> Fix compatibility issues with cirq dev

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.test.cc, src/stim/simulators/tableau_simulator.cc, src/stim/simulators/tableau_simulator.h, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator.test.cc, src/stim/simulators/tableau_simulator_pybind_test.py, src/stim/stabilizers/tableau.h, src/stim/stabilizers/tableau.test.cc, src/stim/stabilizers/tableau_specialized_prepend.cc
- Also: fix circuit's not fusing operations at boundaries when concatenated using `+`
Fixes https://github.com/quantumlib/Stim/issues/261
Fixes https://github.com/quantumlib/Stim/issues/130
=> Add `TableauSimulator.do_{circuit,pauli_string,tableau}`

doc/gates.md, doc/usage_command_line.md, src/stim/circuit/circuit.cc, src/stim/circuit/gate_data_noisy.cc, src/stim/dem/detector_error_model.cc, src/stim/dem/detector_error_model.h, src/stim/dem/detector_error_model.test.cc, src/stim/help.cc, src/stim/main_namespaced.test.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.h, src/stim/simulators/error_analyzer.test.cc, src/stim/simulators/error_matcher.cc
- Add `stim::DetectorErrorModel::rounded` (but don't expose to python as it doesn't work too well)
Fixes https://github.com/quantumlib/Stim/issues/190
=> Add minimal support for ELSE_CORRELATED_ERROR

.github/workflows/ci.yml, doc/developer_documentation.md, doc/python_api_reference_vDev.md, doc/stim.pyi, doctest_proper.py, glue/cirq/stimcirq/__init__.py, glue/python/generate_api_reference.py, glue/python/generate_stub_file.py, glue/python/src/stim/__init__.pyi, glue/sample/src/sinter/plotting.py, glue/zx/stimzx/__init__.py, glue/zx/stimzx/_text_diagram_parsing.py, setup.py, src/stim/circuit/circuit.pybind.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/io/read_write.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/stim.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator_pybind_test.py, src/stim/stabilizers/tableau.pybind.cc
- Fix doctests not being run by continuous integration
- Add a `doctest_proper.py` script for running doctests and actually including values added at import time
- Fix the doctest failures accumulated due to the fact that they weren't even being checked
- Rewrite `generate_api_reference.py` to have output more like the generated `stim.pyi` stubs file
- Add `stim.TableauSimulator.{h_xz,cx,zcx,zcy,zcz}` gate alias methods
- Add `stim.TableauSimulator.{c_xyz,c_zyx}` gate methods
- Add `stim.TableauSimulator.num_qubits`
Fixes https://github.com/quantumlib/Stim/issues/275
=> Fix remaining issues for v1.9

CMakeLists.txt, doc/gates.md, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/generate_api_reference.py, glue/python/generate_stub_file.py, glue/python/src/stim/__init__.pyi, glue/sample/requirements.txt, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.test.cc, src/stim/circuit/gate_data.h, src/stim/circuit/gate_data_annotations.cc, src/stim/circuit/gate_data_blocks.cc, src/stim/circuit/gate_data_collapsing.cc, src/stim/circuit/gate_data_noisy.cc, src/stim/help.cc, src/stim/mem/simd_compat.test.cc, src/stim/simulators/tableau_simulator.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator_pybind_test.py, src/stim/simulators/vector_simulator.cc, src/stim/simulators/vector_simulator.h, src/stim/simulators/vector_simulator.test.cc, src/stim/stabilizers/conversions.cc, src/stim/stabilizers/conversions.h, src/stim/stabilizers/conversions.test.cc, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_pybind_test.py
Python changes:
- Add `stim.Tableau.from_unitary_matrix`
- Add `stim.Tableau.from_circuit`
- Add `stim.Tableau.to_circuit`
- Add `stim.TableauSimulator.set_state_from_stabilizers`
- Add `stim.TableauSimulator.set_state_from_state_vector`
Doc changes:
- Polish R,MR,M gate docs
- Remove some redundant ticks in gate docs
- Mention that two qubit gate unitaries are little endian in gate docs
- Update API generation to spread signatures over multiple lines
C++ changes:
- Add `stim::GATE_IS_RESET` data flag
- Add `stim::VectorSimulator::smooth_stabilizer_state`
- Add `stim::stabilizer_state_vector_to_circuit`
- Add `stim::circuit_to_tableau`
- Add `stim::circuit_to_output_state_vector`
- Add `stim::floor_lg2`
- Add `stim::is_power_of_2`
- Add `stim::stabilizers_to_tableau`
- Add …
=> Add several Tableau conversions + misc

.github/workflows/ci.yml, dev/clean_build_files.sh, dev/regen_docs.sh, doc/developer_documentation.md, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/generate_stub_file.py, glue/python/src/stim/__init__.pyi, glue/sample/src/sinter/_worker_test.py, setup.py, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_gate_target.pybind.cc, src/stim/circuit/circuit_instruction.pybind.cc, src/stim/circuit/circuit_repeat_block.pybind.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model.pybind.h, src/stim/dem/detector_error_model_instruction.pybind.cc, src/stim/dem/detector_error_model_repeat_block.pybind.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/io/read_write.pybind.cc, src/stim/py/base.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/stim.pybind.cc, src/stim/simulators/dem_sampler.pybind.cc, src/stim/simulators/matched_error.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/tableau.pybind.cc
- Rewrite all doc strings to respect the 80 column guide (OOF that one was rough...)
- Add a CI check that ensures `doc/stim.pyi` executes (ensuring it is valid well formed python)
- Make pybind verify doc string lines are at most 80 characters
- Verify no C++-style `stim::` appears in python docstrings
- Add `dev/regen_docs.sh` script
Fixes https://github.com/quantumlib/Stim/issues/327
Fixes https://github.com/quantumlib/Stim/issues/326
Fixes https://github.com/quantumlib/Stim/issues/321
Fixes https://github.com/quantumlib/Stim/issues/317
Fixes https://github.com/quantumlib/Stim/issues/313
Fixes https://github.com/quantumlib/Stim/issues/311
Fixes https://github.com/quantumlib/Stim/issues/310
=> Docstring cleanup pass

.bazelrc
By default, one has to look for test output in a test log file.
=> Make bazel display test errors by default

doc/python_api_reference_vDev.md, doc/stim.pyi, file_lists/python_api_files, glue/python/generate_stub_file.py, glue/python/src/stim/__init__.pyi, src/stim/io/read_write.pybind.cc, src/stim/io/read_write.pybind.h, src/stim/py/numpy.pybind.cc, src/stim/py/numpy.pybind.h, src/stim/simulators/dem_sampler.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/pauli_string_pybind_test.py, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_pybind_test.py
- Fix some spurious empty lines in the api reference and stub file
- Move numpy-vs-simd utility methods to `stim/py/numpy.pybind.{h,cc}`
Fixes of https://github.com/quantumlib/Stim/issues/355
=> Add stim.{PauliString,Tableau}.{to,from}_numpy

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/io/read_write.pybind.cc, src/stim/py/base.pybind.h, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.h, src/stim/py/compiled_detector_sampler_pybind_test.py, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.h, src/stim/py/compiled_measurement_sampler_pybind_test.py, src/stim/py/numpy.pybind.cc, src/stim/py/numpy.pybind.h, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/tableau.pybind.cc
- Use pybind11::capsure to own memory instead of relying on implicit redundant copies from readonly buffers
- Add "bit_packed=False" argument to `stim.Compiled{Measurement,Detector}Sampler.sample`
- Deprecate `stim.Compiled{Measurement,Detectpr}Sampler.sample_bit_packed`
- Fix a typo in the `stim.Tableau.to_numpy` doc string
Example benefit: for small tableaus, stim.Tableau.to_numpy improved from 32us to 2us
=> Speed up numpy output methods

glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_test.py, glue/sample/src/sinter/_plotting.py, glue/sample/src/sinter/_plotting_test.py, glue/sample/src/sinter/_probability_util.py
- Add command line argument `--failure_unit_name`
- Add command line argument `--failure_units_per_shot_func`
- Add argument `failure_units_per_shot_func` to `sinter.plot_discard_rate`
- Add argument `failure_units_per_shot_func` to `sinter.plot_error_rate`
=> Add `failure_units_per_shot_func` argument to sinter

doc/python_api_reference_vDev.md, doc/stim.pyi, doc/usage_command_line.md, file_lists/python_api_files, file_lists/source_files_no_main, file_lists/test_files, glue/python/generate_stub_file.py, glue/python/src/stim/__init__.pyi, src/stim.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/cmd/command_diagram.cc, src/stim/cmd/command_diagram.pybind.cc, src/stim/cmd/command_diagram.pybind.h, src/stim/diagram/ascii_diagram.cc, src/stim/diagram/base64.cc, src/stim/diagram/base64.h, src/stim/diagram/base64.test.cc, src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.h, src/stim/diagram/detector_slice/detector_slice_set.test.cc, src/stim/diagram/diagram_util.cc, src/stim/diagram/timeline/timeline_ascii_drawer.test.cc, src/stim/diagram/timeline/timeline_svg_drawer.cc, src/stim/diagram/timeline/timeline_svg_drawer.test.cc, src/stim/py/stim.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc
- Change TICK convention so that first TICK is index 1 instead of index 0
- Fix circuit timeline svg diagrams using width/height instead of viewbox property
- Add stim._DiagramHelper with HTML viewers for text and SVG
- Add a bit of whitespace padding around svg timeline diagrams
=> Add stim.Circuit.diagram

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/arg_parse.test.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit.test.cc, src/stim/cmd/command_analyze_errors.cc, src/stim/cmd/command_detect.cc, src/stim/cmd/command_diagram.cc, src/stim/cmd/command_explain_errors.cc, src/stim/cmd/command_m2d.cc, src/stim/cmd/command_sample.cc, src/stim/cmd/command_sample_dem.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model.test.cc, src/stim/diagram/graph/match_graph_3d_drawer.test.cc, src/stim/diagram/graph/match_graph_svg_drawer.test.cc, src/stim/diagram/timeline/timeline_3d_drawer.test.cc, src/stim/diagram/timeline/timeline_svg_drawer.test.cc, src/stim/io/measure_record_reader.h, src/stim/io/measure_record_reader.test.cc, src/stim/io/read_write.pybind.cc, src/stim/io/read_write_pytest.py, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/simulators/dem_sampler.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/measurements_to_detection_events_test.py, src/stim/test_util.test.cc
- `read_shot_data_file` had a segfault due to miscalculating buffer size and also offsets
- Files were being opened in `"r"` mode instead of `"rb"`, resulting in lost bytes on windows due to conversion from `\r\n` to `\n`
- Files were being opened in `"w"` mode instead of `"wb"`, resulting in potential extra bytes on windows due to conversion from `\n` to `\r\n`
- Fix `\r` character not being treated as whitespace when parsing
Fixes https://github.com/quantumlib/Stim/issues/377
=> Fix various file io bugs

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/gate_target.cc, src/stim/circuit/gate_target.h, src/stim/circuit/gate_target.test.cc, src/stim/simulators/tableau_simulator.cc, src/stim/simulators/tableau_simulator.h, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator_pybind_test.py
- Add `GateTarget::has_qubit_value`
Fixes https://github.com/quantumlib/Stim/issues/285
=> Add support for circuit instructions to `stim.TableauSimulator.do`

src/stim/circuit/circuit.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/dem/detector_error_model.cc, src/stim/stabilizers/pauli_string.cc
This was causing crashes in debug builds for `stim.Circuit()[::-1]`
=> Fix slice start assertions not being conditional on non-zero length

src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_gate_target.pybind.cc, src/stim/circuit/circuit_instruction.pybind.cc, src/stim/circuit/circuit_repeat_block.pybind.cc, src/stim/cmd/command_diagram.pybind.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model_instruction.pybind.cc, src/stim/dem/detector_error_model_repeat_block.pybind.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/diagram/gate_data_svg.cc, src/stim/io/read_write.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/stim.pybind.cc, src/stim/simulators/dem_sampler.pybind.cc, src/stim/simulators/matched_error.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_iter.pybind.cc
- Was breaking compatibility with -std=C++20
- Doesn't appear to have been doing anything anyways, in terms of what ends up in memory
=> Remove 'u8' prefixes from strings

.github/workflows/ci.yml, glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_plot_test.py, glue/sample/src/sinter/_plotting.py
- Backwards-compatibly add a 'all stats in group' parameter to the python API version
- Add several more available values to `--plot_args_func` in `sinter plot`
=> Add ability to access group stats in `plot_args_func`

src/stim/stabilizers/pauli_string.pybind.cc
Fixes a typo in the error message for `sign` attribute of a PauliString.
The allowable values are [1, -1, 1j, -1j]
=> Fix error message with invalid sign value

.gitignore, glue/sample/src/sinter/_collection.py, glue/sample/src/sinter/_main_collect.py, src/stim/diagram/gate_data_svg.cc, src/stim/diagram/gate_data_svg.h, src/stim/diagram/timeline/timeline_svg_drawer.cc, testdata/collapsing.svg, testdata/command_diagram_timeline.svg, testdata/command_diagram_timeline_tick1.svg, testdata/command_diagram_timeline_tick1_3.svg, testdata/lattice_surgery_cnot.svg, testdata/repeat.svg, testdata/repetition_code.svg, testdata/single_qubits_gates.svg, testdata/surface_code.svg, testdata/surface_code_full_time_detector_slice.svg, testdata/surface_code_time_detector_slice.svg, testdata/surface_code_time_slice.svg, testdata/tick.svg, testdata/two_qubits_gates.svg
This generalizes (and obsoletes) the clunky "depend on 4th coordinate being non-zero" flag
- Also fixed a few doc typos
- Also made some tweaks to the look of detector slice diagrams
=> Add `--postselected_detectors_predicate` option to sinter

src/stim/simulators/tableau_simulator.cc, src/stim/simulators/tableau_simulator.test.cc, src/stim/stabilizers/pauli_string.cc, src/stim/stabilizers/pauli_string.h, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/pauli_string.test.cc, src/stim/stabilizers/pauli_string_ref.cc, src/stim/stabilizers/pauli_string_ref.h, src/stim/stabilizers/tableau.cc, src/stim/stabilizers/tableau.h, src/stim/stabilizers/tableau.test.cc
- I thought it wouldn't matter because the step size was at least 64, but a user running sims with hundreds of thousands of qubits noticed it being very slow due to this
- Add a required "resize pad factor" to the underlying C++ resizing methods for pauli strings and tableaus, and set it to `1.1` in most cases
- Break the invariant that the backing storage for tableaus and pauli strings must be exactly minimum after simd alignment (still a requirement for the PauliStringRef class; now explicitly asserted)
=> Fix quadratic overhead when iteratively resizing Pauli strings and tableaus

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, glue/sample/src/sinter/_plotting.py, glue/sample/src/sinter/_plotting_test.py, src/stim/io/read_write.pybind.cc, src/stim/io/read_write_pytest.py, src/stim/simulators/dem_sampler.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.h, src/stim/simulators/measurements_to_detection_events_test.py, src/stim/stabilizers/conversions.cc, src/stim/stabilizers/conversions.test.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/pauli_string.pybind.h, src/stim/stabilizers/pauli_string_pybind_test.py
- Fix `stim.Tableau.from_stabilizers` not failing when given anticommuting stabilizers
- Add `unsigned` option to `stim.PauliString.from_unitary_matrix`
- Add prefered name `bit_packed` over legacy `bit_pack_result` to `CompiledMeasurementsToDetectionEventsConverter.convert`
- Add `separate_observables=False` to `stim.read_shot_data_file`
Fixes https://github.com/quantumlib/Stim/issues/468
Fixes https://github.com/quantumlib/Stim/issues/462
Fixes https://github.com/quantumlib/Stim/issues/459
Fixes https://github.com/quantumlib/Stim/issues/425
Fixes https://github.com/quantumlib/Stim/issues/413
Fixes https://github.com/quantumlib/Stim/issues/408
=> Squash issues in preparation for v1.11

doc/python_api_reference_vDev.md, doc/stim.pyi, doc/usage_command_line.md, glue/python/src/stim/__init__.pyi, src/stim/cmd/command_m2d.cc, src/stim/cmd/command_m2d.test.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator_pybind_test.py, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_pybind_test.py
- Add `stim.Tableau.{x,y,z}_sign`
- Add `stim.TableauSimulator.{x_error,y_error,z_error,depolarize1,depolarize2}`
- Add `--ran_without_feedback` option to `stim m2d`
Fixes https://github.com/quantumlib/Stim/issues/398
Fixes https://github.com/quantumlib/Stim/issues/411
Fixes https://github.com/quantumlib/Stim/issues/286
=> Squash more issues in preparation for v1.11

src/stim/circuit/circuit.cc, src/stim/cmd/command_sample.test.cc, src/stim/diagram/circuit_timeline_helper.cc, src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/mem/fixed_cap_vector.h, src/stim/stabilizers/conversions.cc
- Use stable_sort in diagrams to avoid accidental reordering
- Fix re-checking for circuit operation fusing after fusing was done
- Increase sample counts in statistical tests
- Fix using &vector[vector.size()] instead of vector.data() + vector.size() to get end ptr of vector data
=> Fix some flaky tests

doc/gates.md, src/stim/circuit/gate_data_swaps.cc
=> Fix SSSS=I redundancies in example decompositions

glue/cirq/stimcirq/_cirq_to_stim.py, glue/cirq/stimcirq/_cirq_to_stim_test.py
In particular, tagged loops will make following check fail
```python
if isinstance(op, cirq.CircuitOperation):
self.process_circuit_operation_into_repeat_block(op)
continue
```
Since the conversion function seems to be ignoring the tags, I simply untagged them at the beginning of the loop and let everything else proceed with the same current assumption of untagged operations.
=> Fix the cirq to stim conversion for circuits with tagged operations

glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_stim_to_cirq_test.py
This modification ensures that `cirq.CircuitOperation` are always isolated in their own `cirq.Moment`
=> Separate repeat block in their own moment

src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit.test.cc, src/stim/circuit/gate_data.cc, src/stim/circuit/gate_data.h, src/stim/circuit/gate_data.test.cc, src/stim/circuit/gate_data_annotations.cc, src/stim/circuit/gate_data_blocks.cc, src/stim/circuit/gate_data_collapsing.cc, src/stim/circuit/gate_data_controlled.cc, src/stim/circuit/gate_data_hada.cc, src/stim/circuit/gate_data_noisy.cc, src/stim/circuit/gate_data_pauli.cc, src/stim/circuit/gate_data_period_3.cc, src/stim/circuit/gate_data_period_4.cc, src/stim/circuit/gate_data_pp.cc, src/stim/circuit/gate_data_swaps.cc, src/stim/stabilizers/pauli_string.test.cc, src/stim/stabilizers/pauli_string_ref.cc
- Ignore annotations like TICK and OBSERVABLE_INCLUDE instead of failing if they are present
- When a reset or measure-reset operation is present, only fail if the pauli string actually touches it with a non-identity term
- When a measure operation is present, only fail if the pauli string anticommutes with it
- Add a "allow_weak_inverse" argument to stim::Circuit::inverse, that makes it use approximate inversion where e.g. noise is its own inverse and a measurement is its own inverse
- Added a "best guess inverse" field to Gate objects
- Make stim::Circuit::inverse work on SHIFT_COORDS
- Refactored stim::Gate::inverse to use the inverse data added to all gates
- Added GATE_HAS_NO_EFFECT_ON_QUBITS flag data to gates
Fixes https://github.com/quantumlib/Stim/issues/497 Fixes …
=> Make stim.PauliString.before/after work in more situations

glue/sample/src/sinter/_decoding_pymatching_v2.py, src/stim/io/measure_record_batch.cc, src/stim/io/measure_record_batch.h, src/stim/mem/simd_bit_table.h, src/stim/mem/simd_bit_table.inl, src/stim/mem/simd_bit_table.test.cc, src/stim/mem/simd_bits.h, src/stim/mem/simd_bits.inl, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.h, src/stim/py/compiled_detector_sampler_pybind_test.py, src/stim/simulators/frame_simulator.cc, src/stim/simulators/frame_simulator.h, src/stim/simulators/frame_simulator.test.cc
- Time to re-sample 2^14 shots from a d=13 r=39 surface code improved from ~1.8s to ~1.2s
- Add stim::FrameSimulator::configure_for
- Add stim::{simd_bits,simd_bit_table,etc}::destructive_resize
=> Keep stim.CompiledDetectorSampler's FrameSim cached

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/py/compiled_measurement_sampler.pybind.cc, src/stim/py/compiled_measurement_sampler.pybind.h, src/stim/py/compiled_measurement_sampler_pybind_test.py, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator_pybind_test.py
Addresses #531 and #532. compile_sampler now accepts reference_sample keyword argument which defaults to None. Also exposes the TableauSimulator::reference_sample method to pybind which is useful for checking that passing in this reference sample reproduces to current behaviour when skip_reference_sample is False.
=> Allow reference_sample to be passed as an argument to sampler.

doc/sinter_api.md, doc/sinter_command_line.md, glue/sample/README.md, glue/sample/src/sinter/_anon_task_stats.py, glue/sample/src/sinter/_collection.py, glue/sample/src/sinter/_collection_tracker_for_single_task.py, glue/sample/src/sinter/_collection_work_manager.py, glue/sample/src/sinter/_csv_out.py, glue/sample/src/sinter/_decoding.py, glue/sample/src/sinter/_decoding_test.py, glue/sample/src/sinter/_existing_data.py, glue/sample/src/sinter/_main_collect.py, glue/sample/src/sinter/_main_collect_test.py, glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_plot_test.py, glue/sample/src/sinter/_main_predict_test.py, glue/sample/src/sinter/_task_stats.py, glue/sample/src/sinter/_worker.py, glue/sample/src/sinter/_worker_test.py
- Add `--split_errors` option to `sinter collect` to store errors keyed by obs symptom instead of just recording if anything failed at all
- Add `--split_errors` option to `sinter plot` to split compound errors into multiple separate rows
- Add `sinter.{AnonTaskStats,TaskStats}classified_errors` field
- Add `split_errors=False` argument to `sinter.{collect,iter_collect}
- Modify CSV reading and writing to expand errors column into classified errors when needed
- Add `m` value to sinter plot command line lambdas
- Add sinter command line usage documentation
In stats files split errors look like this, with what would have been an integer number of errors expanded into a dictionary of failed observable to count like `{"EE":3,"E_":41,"_E":27}`:
```
4124,"{""EE"":3,""E_"":41,""_E"":27}",0, …
```
=> Add `split_errors` options to sinter

.github/workflows/ci.yml, dev/gen_sinter_api_reference.py, doc/sinter_api.md, glue/sample/README.md, glue/sample/src/sinter/_anon_task_stats.py, glue/sample/src/sinter/_anon_task_stats_test.py, glue/sample/src/sinter/_collection.py, glue/sample/src/sinter/_collection_tracker_for_single_task.py, glue/sample/src/sinter/_collection_work_manager.py, glue/sample/src/sinter/_csv_out.py, glue/sample/src/sinter/_decoding.py, glue/sample/src/sinter/_decoding_test.py, glue/sample/src/sinter/_existing_data.py, glue/sample/src/sinter/_existing_data_test.py, glue/sample/src/sinter/_main_collect.py, glue/sample/src/sinter/_main_collect_test.py, glue/sample/src/sinter/_main_combine_test.py, glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_plot_test.py, glue/sample/src/sinter/_task_stats.py, glue/sample/src/sinter/_task_stats_test.py, glue/sample/src/sinter/_worker.py, glue/sample/src/sinter/_worker_test.py
- Obsoletes the multi-value error column option; so drop it
- Replace `sinter collect --split_errors` option with `--count_observable_error_combos`
- Add `sinter collect --count_detection_events` option
- Replace `sinter plot --split_errors` option with `--count_observable_error_combos`
Fixes https://github.com/quantumlib/Stim/issues/406
=> Add a `custom_counts` column to sinter

glue/sample/src/sinter/_task_stats.py
[Old python](https://stackoverflow.com/questions/15844714/why-am-i-getting-an-error-message-in-python-cannot-import-name-nonetype) used to have `NoneType = type(None)` definition in the `types` module. In python 3 the module doesn't provide `NoneType` anymore until python 3.10 when it's back again...
```console
$ python3.8
Python 3.8.7 (default, Dec 22 2020, 10:37:26) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from types import NoneType
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'NoneType' from 'types' (/usr/lib/python3.8/types.py)
>>> 
$ python3.10
Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more …
```
=> Don't rely on types module to supply NoneType

.gitignore, BUILD, WORKSPACE, doc/sinter_api.md, doc/sinter_command_line.md, glue/sample/src/sinter/_decoding.py, glue/sample/src/sinter/_decoding_decoder_class.py, glue/sample/src/sinter/_decoding_test.py, glue/sample/src/sinter/_main_collect.py, glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_plot_test.py, glue/sample/src/sinter/_task_stats.py
- Bump versions of dependencies in WORKSPACE
- Fix disk decoding fallback being within an except block, complicating error messages
- Change splitting to keep all custom counts but highlight the one that replaced errors with extra properties
- Require user to list the custom counts they want
- Allow multiple custom decoder module functions
=> Refactor `sinter plot --split_custom_counts` into `--custom_error_count_keys`

src/stim/circuit/gate_data.test.cc, src/stim/cmd/command_gen.test.cc, src/stim/probability_util.test.cc, src/stim/stabilizers/conversions.test.cc
A simple change to testing, most of which was enabled by #548.
Now that the key simulators have been templatised (#548), the last few conversion tests could be moved over to use `TEST_EACH_WORD_SIZE_W` as described in a comment in #559. As an aside, the remaining circuit, cmd and probability tests have also been moved over to be tested across all widths.
=> Test conversions on all SIMD widths

file_lists/source_files_no_main, src/stim/cmd/command_sample_dem.cc, src/stim/dem/detector_error_model.pybind.cc, src/stim/simulators/dem_sampler.h, src/stim/simulators/dem_sampler.inl, src/stim/simulators/dem_sampler.perf.cc, src/stim/simulators/dem_sampler.pybind.cc, src/stim/simulators/dem_sampler.pybind.h, src/stim/simulators/dem_sampler.test.cc, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/simulators/sparse_rev_frame_tracker.h, src/stim/simulators/sparse_rev_frame_tracker.test.cc
If merged, this PR proposes to build on #548 by extending templatisation of SIMD widths to two further simulators.
Firstly, the `DemSampler` has become a class template. Second, template functions have been added, where appropriate, to the `SparseUnsignedRevFrameTracker`. As before, the motivation for this was to remove the use of hardcoded SIMD widths. Templatisation also facilitates unit testing across all SIMD widths via `TEST_EACH_WORD_SIZE_W`.
=> Templatise the `DemSampler` and `SparseUnsignedRevFrameTracker`

src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.h, src/stim/diagram/detector_slice/detector_slice_set.test.cc
Fixes https://github.com/quantumlib/Stim/issues/553
=> Loosen colinearity check used in diagrams when deciding to use curved paths

src/stim/circuit/circuit_pybind_test.py, src/stim/cmd/command_diagram.pybind.cc, src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.h
- Fix the fact that it doesn't take DemTarget instances
- Allow passing strings like "D5" and "L0"
- Allow passing an individual filter instead of a list
- Allow saying 'detslice' instead of 'detslice-svg'
Fixes https://github.com/quantumlib/Stim/issues/616
=> Increase flexibility of stim.Circuit.diagram filter_coords args

glue/cirq/stimcirq/__init__.py, glue/cirq/stimcirq/_cirq_to_stim.py, glue/cirq/stimcirq/_cirq_to_stim_test.py, glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_two_qubit_asymmetric_depolarize.py, glue/cirq/stimcirq/_two_qubit_asymmetric_depolarize_test.py
- Deprecate usage of `stimcirq.TwoQubitAsymmetricDepolarizingChannel` in favor of cirq's native asymmetric channel
- Check number of qubits when converting from cirq's asymmetric noise channel
Fixes https://github.com/quantumlib/Stim/issues/625
=> Fix stimcirq handling of 2-qubit cirq.AsymmetricDepolarizingChannel

file_lists/source_files_no_main, src/stim.h, src/stim/dem/dem_instruction.cc, src/stim/dem/dem_instruction.h, src/stim/dem/detector_error_model.cc, src/stim/dem/detector_error_model.h, src/stim/dem/detector_error_model.pybind.cc, src/stim/main_namespaced.test.cc, src/stim/main_namespaced.test.h, src/stim/simulators/error_analyzer.cc
- Extract `dem_instruction.{h,cc}` files
- Fix test util `run_captured_stim_main` not having a way to specify `--in` for an empty file anymore
=> Add `stim::DemInstruction` repeat block helper methods

src/stim/mem/sparse_xor_vec.h, src/stim/mem/sparse_xor_vec.perf.cc, src/stim/mem/sparse_xor_vec.test.cc
- This was going like 100x too slow due to delegating to the list case that used a buffer on the stack
=> Speed up SparseXorVec.xor_item

src/stim/mem/simd_bits.test.cc, src/stim/mem/simd_bits_range_ref.inl
Caught this when trying to address #598.
=> Fix bug with simd_bits +=.

src/stim/simulators/dem_sampler.h, src/stim/simulators/dem_sampler.inl, src/stim/simulators/dem_sampler.test.cc
- Safety against accidental duplication of rng states
=> Make `stim::DemSampler()` take its rng by forced rvalue

.github/workflows/ci.yml, CMakeLists.txt, WORKSPACE, glue/sample/src/sinter/_main_plot.py, pyproject.toml, src/stim/benchmark_main.perf.cc, src/stim/benchmark_util.perf.h
- Fix a static initialization order dependency in `stim_benchmark`
- Remove `stim_benchmark` from `make install`
- Rearrange marker ordering in sinter to defer the time until  visually ambiguous case  occurs (in both color and shape)
- Fix X axis only applying to first subplot in a sinter plot, instead of all
- Bump pybind version
- Add python 3.12 builds
Fixes https://github.com/quantumlib/Stim/issues/623
=> Add python 3.12 build along with various fixes

doc/gates.md, src/stim/circuit/gate_data.cc, src/stim/circuit/gate_data.h, src/stim/circuit/gate_data.test.cc, src/stim/circuit/gate_data_annotations.cc, src/stim/circuit/gate_data_blocks.cc, src/stim/circuit/gate_data_collapsing.cc, src/stim/circuit/gate_data_controlled.cc, src/stim/circuit/gate_data_hada.cc, src/stim/circuit/gate_data_heralded.cc, src/stim/circuit/gate_data_noisy.cc, src/stim/circuit/gate_data_pair_measure.cc, src/stim/circuit/gate_data_pauli.cc, src/stim/circuit/gate_data_period_3.cc, src/stim/circuit/gate_data_period_4.cc, src/stim/circuit/gate_data_pp.cc, src/stim/circuit/gate_data_swaps.cc, src/stim/cmd/command_help.cc
- Inline `struct stim::ExtraGateData` struct into `struct stim::Gate`
- Add `stim::Gate::to_axis_angle`
- Add `stim::Gate::to_euler_angles`
- Change gate docs to use `°` instead of `degrees`
- Add tests verifying axis-angle and euler-angle decompositions
=> Add `Bloch Rotation (Euler angles)` to gate doc

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/export_qasm.cc, src/stim/diagram/timeline/timeline_ascii_drawer.test.cc, src/stim/simulators/tableau_simulator.inl, src/stim/stabilizers/tableau.h, src/stim/stabilizers/tableau.inl, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_pybind_test.py
Fixes https://github.com/quantumlib/Stim/issues/637
=> Add stim.Tableau.to_stabilizers

BUILD
This makes autocomplete work when testing and debugging wheels during developments.
=> Add `stim.pyi` to bazel dev build

src/stim/simulators/tableau_simulator.inl, src/stim/simulators/tableau_simulator.test.cc, src/stim/simulators/vector_simulator.cc, src/stim/simulators/vector_simulator.h, src/stim/simulators/vector_simulator.test.cc, src/stim/stabilizers/conversions.cc, src/stim/stabilizers/conversions.inl, src/stim/stabilizers/tableau.test.cc
Not really that important... more a point of principle. Just less wasteful.
=> Refactor `stim::VectorSimulator` to take `GateType` enums instead of gate names

doc/python_api_reference_vDev.md, doc/stim.pyi, file_lists/source_files_no_main, file_lists/test_files, glue/python/src/stim/__init__.pyi, src/stim.h, src/stim/simulators/graph_simulator.cc, src/stim/simulators/graph_simulator.h, src/stim/simulators/graph_simulator.test.cc, src/stim/stabilizers/conversions.h, src/stim/stabilizers/conversions.inl, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_pybind_test.py
- Add `stim::GraphSimulator` with support for unitary operations
Fixes https://github.com/quantumlib/Stim/issues/647
=> Add `stim.Tableau.to_circuit("graph_state")`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/javascript/pauli_string.js.cc, glue/python/src/stim/__init__.pyi, src/stim/arg_parse.cc, src/stim/arg_parse.h, src/stim/arg_parse.test.cc, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/circuit/stabilizer_flow.h, src/stim/circuit/stabilizer_flow.inl, src/stim/circuit/stabilizer_flow.test.cc, src/stim/stabilizers/pauli_string.h, src/stim/stabilizers/pauli_string.inl
- Refactor a few initial C++ methods to use `std::string_view` instead of `const char *` or `const std::string &`
=> Add `shorthand` argument to `stim.Circuit.has_flow`

doc/python_api_reference_vDev.md, doc/stim.pyi, file_lists/source_files_no_main, file_lists/test_files, glue/python/src/stim/__init__.pyi, glue/sample/src/sinter/_task.py, src/stim.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/stabilizer_flow.inl, src/stim/dem/detector_error_model.pybind.cc, src/stim/simulators/frame_simulator.pybind.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/conversions.inl, src/stim/stabilizers/flex_pauli_string.cc, src/stim/stabilizers/flex_pauli_string.h, src/stim/stabilizers/flex_pauli_string.test.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/pauli_string.pybind.h, src/stim/stabilizers/pauli_string_iter.pybind.cc, src/stim/stabilizers/pauli_string_pybind_test.py, src/stim/stabilizers/tableau.pybind.cc
- Also fix `sinter.Task.strong_id` not correctly checking for circuit not being set
- Fix `stim.PauliString.__init__` specifying pybind11 overloads instead of manually doing resolution.
- This notably improved the documentation of the method.
- Force positional arg on the init argument, but silently maintain backwards compatibility with old keyword
- Fix `stim.PauliString.from_unitary_matrix` signature typo `float` -> `complex`
- Fix `stim.PauliString.before` signature typo `after` -> `before`
=> Refactor `stim_pybind::PyPaulString` -> `stim::FlexPauliString`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/simulators/frame_simulator.pybind.cc, src/stim/simulators/frame_simulator_pybind_test.py
Addresses part of #653
Gives a general method for applying errors with 2D masks, key for speeding up interactive use of the flip simulator
=> Add `stim.FlipSimulator.broadcast_pauli_errors`

src/stim/py/march.pybind.cc
This patch enables pip installation from source on IBM PowerPC in a way that is consistent with what is in place for Arm architectures.
=> Enable pip installation from source on IBM PowerPC

src/stim/stabilizers/conversions.inl, src/stim/stabilizers/conversions.perf.cc
- 144 qubit case went from 5000 micros to 500 micros
- 576 qubit case went from 2500 millis to 200 millis
=> Speed up `stim.Tableau.from_stabilizers` another 10x

src/stim/mem/simd_word.test.cc, src/stim/simulators/tableau_simulator.test.cc, src/stim/stabilizers/conversions.inl, src/stim/stabilizers/conversions.test.cc, src/stim/stabilizers/tableau.test.cc, src/stim/stabilizers/tableau_iter.test.cc
- Switch to streaming computations of the gates
- Improve the anticommutation check from O(n^2) additional work to O(n) additional work
- Fix a sizing error and test that it's fixed
- Cut costs on slowest test
=> Clean up `stim.Tableau.from_stabilizers` a bit

doc/python_api_reference_vDev.md, doc/stim.pyi, file_lists/source_files_no_main, file_lists/test_files, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/cmd/command_help.cc, src/stim/search/sat/wcnf.cc, src/stim/search/sat/wcnf.h, src/stim/search/sat/wcnf.test.cc, src/stim/search/search.h, src/stim/simulators/error_matcher.cc
Adds a generator that outputs a .wcnf file string in [WDIMACS format](http://www.maxhs.org/docs/wdimacs.html).
Added a few tests as well.
Here is a demo:
**Step 1:** Generate the WCNF file
```python
import stim
c = stim.Circuit.generated(
"surface_code:rotated_memory_z",
distance=5,
rounds=2,
after_clifford_depolarization=0.001,
)
wcnf = c.shortest_error_sat_problem()
with open('d5problem.wcnf', 'w') as outfile:
outfile.write(wcnf)
```
**Step 2:** Fetch a solver from the [2023 maxSAT competition](https://maxsat-evaluations.github.io/2023/)
```bash
wget https://maxsat-evaluations.github.io/2023/mse23-solver-src/exact/CASHWMaxSAT-CorePlus.zip
unzip CASHWMaxSAT-CorePlus.zip
```
**Step 3:** Run the solver on the produced file
```bash
time ./CASHWMaxSAT-CorePlus/bin/cashwmaxsatcoreplus -bm -m …
```
=> Add `stim.Circuit.{shortest,likeliest}_error_sat_problem`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/circuit/gate_decomposition.cc, src/stim/circuit/gate_decomposition.h, src/stim/circuit/gate_decomposition.test.cc, src/stim/search/hyper/algo.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/frame_simulator.inl, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/simulators/sparse_rev_frame_tracker.test.cc, src/stim/simulators/tableau_simulator.inl
- The `stim::decompose_pair_instruction_into_segments_with_single_use_controls` was not guaranteeing the invariants actually used by code calling the method
- The detecting regions of circuits with MXX/MYY/MZZ operations were often wrong if the same qubit was used multiple times in the same instruction
- Refactored `stim::decompose_pair_instruction_into_segments_with_single_use_controls` into `stim::decompose_pair_instruction_into_disjoint_segments`
- Also fixed a hard-to-reproduce issue where the hyper search could use the same error twice
=> Fix bad M{XX,YY,ZZ} tracking due to disjoint decomposition

glue/cirq/stimcirq/_cirq_to_stim.py, glue/cirq/stimcirq/_cirq_to_stim_test.py
Currently in `main` when we convert a cirq circuit to stim with a `CircuitOperation` with a single repetition (or with `flatten=True`) no TICK instructions are inserted since the moments are removed in the `cirq.decompose_once(op)` command.
=> Fix cirq-to-stim conversion not adding `TICK`s for multi-moment single-rep `CircuitOperation`s

src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/simulators/transform_without_feedback.cc, src/stim/simulators/transform_without_feedback.test.cc
- When a pure-feedback instruction was between two instructions of the same type, they were fused when partially reversed when the feedback instruction was removed
- Fixed by turning off fusion while the circuit is only partially reversed
- Fixes https://github.com/quantumlib/Stim/issues/730
=> Fix interleaved feedback being removed incorrectly

src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.h, src/stim/diagram/detector_slice/detector_slice_set.test.cc, src/stim/diagram/timeline/timeline_svg_drawer.test.cc, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/simulators/sparse_rev_frame_tracker.h, src/stim/simulators/sparse_rev_frame_tracker.test.cc, src/stim/stabilizers/flow.inl, testdata/anticommuting_detslice.svg
- Give better error messages when SparseRevTracker hits an anticommutation
Fixes https://github.com/quantumlib/Stim/issues/471
=> Draw anticommutations in detslice diagrams instead of failing to make the diagram

src/stim/gates/gates.h
This ensures that the ids of elements of a default constructed std::array of GateDataMapHashEntry do not have indeterminate values.
=> Ensure that GateDataMapHashEntry is not trivially default-initialized.

src/stim/mem/simd_bits.test.cc, src/stim/stabilizers/pauli_string_iter.pybind.cc
Removes template argument deduction for types that don't have explicit deduction rules.
=> Ensure that stim compiles with clang -Wctad-maybe-unsupported

src/stim/stabilizers/tableau_pybind_test.py, src/stim/util_top/stabilizers_to_tableau.inl
- Include examples when failing
- Fix some anticommutation cases claiming that the issue is the stabilizers are redundant
Fixes https://github.com/quantumlib/Stim/issues/760
=> Improve stim.Tableau.from_stabilizers error messages

file_lists/perf_files, file_lists/source_files_no_main, file_lists/test_files, src/stim.h, src/stim/io/measure_record.cc, src/stim/io/measure_record.h, src/stim/simulators/tableau_simulator.perf.cc, src/stim/util_top/reference_sample_tree.cc, src/stim/util_top/reference_sample_tree.h, src/stim/util_top/reference_sample_tree.inl, src/stim/util_top/reference_sample_tree.perf.cc, src/stim/util_top/reference_sample_tree.test.cc
Get a compressed tree representation of the reference sample by using `stim::ReferenceSampleTree::from_circuit_reference_sample(circuit)`.
The reason for a tree, instead of raw run length encoding, is to support nested loops (e.g. physical surface code rounds repeating within repeated logical operations).
Example test:
```
CircuitGenParameters params(10000, 3, "rotated_memory_x");
auto circuit = generate_surface_code_circuit(params).circuit;
circuit.blocks[0].append_from_text("X 10 11 12 13");
auto ref = ReferenceSampleTree::from_circuit_reference_sample(circuit);
ASSERT_EQ(ref.str(), "1*(''+2*('00000000')+4999*('0110000000110000')+1*('000000000'))");
```
Example benchmark (25 milliseconds to do a distance 31 surface code with a billion rounds):
```
CircuitGenParameters params(1000000000, …
```
=> Add `stim::ReferenceSampleTree` to support loop folded reference sampling

WORKSPACE, dev/util_gen_stub_file.py, doc/gates.md, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, glue/sample/src/sinter/_probability_util.py, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/gates/gate_data_pauli_product.cc, src/stim/simulators/tableau_simulator.pybind.cc
- Also fix an issue where enormous stats cause sinter to fail to plot
- Also fix an issue where circuits with the same blocks could be considered not equal if their internal representation was different
- Also bump pybind version to make numpy 2 start working
- Also fix an issue where the scipy linear regression type was accessed from a private module; use the public API as a fallback
Fixes https://github.com/quantumlib/Stim/issues/780
Fixes https://github.com/quantumlib/Stim/issues/779
=> Add `stim.Circuit.insert` and numpy 2 compat

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit.test.cc, src/stim/stabilizers/pauli_string_pybind_test.py, src/stim/stabilizers/pauli_string_ref.h, src/stim/stabilizers/pauli_string_ref.inl
- Also switch `circuit.insert` to doing auto-fusion of operations
=> Fix PauliString.before reset not working

dev/doctest_proper.py, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/dem/dem_instruction.cc, src/stim/dem/dem_instruction.h, src/stim/dem/detector_error_model_pybind_test.py, src/stim/dem/detector_error_model_repeat_block.pybind.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/dem/detector_error_model_target_pybind_test.py, src/stim/gates/gates.cc, src/stim/gates/gates.h, src/stim/gates/gates.pybind.cc, src/stim/gates/gates.test.cc, src/stim/gates/gates_test.py, src/stim/simulators/matched_error.pybind.cc
- Add some missing example sections to docstrings
- Add a warning about missing example sections when running documentation tests
- Add `stim.GateData.is_symmetric_gate`
- Add `stim.GateData.hadamard_conjugated(unsigned=False)`
- Add `stim.DemTarget.__init__` with support for parsing strings
Fixes https://github.com/quantumlib/Stim/issues/795
=> Add `stim.GateData.{is_symmetric_gate,hadamard_conjugated}`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/cmd/command_diagram.pybind.cc, src/stim/cmd/command_diagram.pybind.h, src/stim/dem/detector_error_model_instruction.pybind.cc, src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.h, src/stim/diagram/timeline/timeline_svg_drawer.cc, src/stim/diagram/timeline/timeline_svg_drawer.h, src/stim/mem/bitword_128_sse.h, src/stim/mem/bitword_256_avx.h, src/stim/mem/bitword_64.h, src/stim/mem/simd_word.test.cc, src/stim/simulators/frame_simulator.pybind.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/tableau.pybind.cc, src/stim/util_top/circuit_vs_amplitudes.cc, testdata/anticommuting_detslice.svg, testdata/bezier_time_slice.svg, testdata/circuit_all_ops_detslice.svg, testdata/circuit_all_ops_timeslice.svg, testdata/circuit_diagram_timeline_svg_chained_loops.svg, testdata/detslice-with-ops_surface_code.svg, testdata/observable_slices.svg, testdata/surface_code_full_time_detector_slice.svg, testdata/surface_code_time_detector_slice.svg, testdata/surface_code_time_slice.svg
- Add "rows" argument to `stim.Circuit.diagram` to control layout of multi-row diagrams
- Add "tick" labels to timeslice diagrams
- Add stim.FlipSimulator.copy
- Add stim.FlipSimulator.reset
Fixes https://github.com/quantumlib/Stim/issues/672
=> Add some `stim.FlipSimulator` methods and diagram niceties

file_lists/test_files, src/stim.h, src/stim/cmd/command_diagram.pybind.cc, src/stim/dem/detector_error_model_target.pybind.cc, src/stim/gates/gates.cc, src/stim/gates/gates.test.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.h, src/stim/simulators/error_analyzer.test.cc, src/stim/simulators/matched_error.pybind.cc, src/stim/util_top/circuit_to_dem.h, src/stim/util_top/circuit_to_dem.test.cc, src/stim/util_top/circuit_vs_amplitudes.cc
- :foreheadslap:
- autoformat
- Add `stim::circuit_to_dem` to the C++ API for easier conversions with named arguments via a struct
- There was a unit test checking this... but it was also permuted. Added unit tests that check it channel by channel.
=> Fix `HERALDED_PAULI_CHANNEL_1` permuting X/Y/Z error argument components

src/stim/diagram/json_obj.cc
* Removing unnecessary `;` on `JsonObj::JsonObj(std::vector<JsonObj>)`.
* Trips off `-Wpedantic` and other warnings.
* Fixing newlines around function definition.
=> Fixing Extra Semicolon

.github/workflows/ci.yml, glue/sample/MANIFEST.in
- Fixes upload-artifact and download-artifact usage to account for their breaking changes
- Fixes sinter not declaring recursive inclusions in its manifest
=> Fix broken artifact upload

src/stim/circuit/circuit_instruction.cc, src/stim/circuit/circuit_pybind_test.py
- Was writing the arguments instead of the targets into the message
Fixes https://github.com/quantumlib/Stim/issues/817
=> Fix odd-target-count-for-two-qubit-gate error message

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/util_top/export_crumble_url.cc, src/stim/util_top/export_crumble_url.h, src/stim/util_top/export_crumble_url.test.cc, src/stim/util_top/export_crumble_url_pybind_test.py
Fixes https://github.com/quantumlib/Stim/issues/806
=> Add `skip_detectors` and `mark` arguments to `stim.Circuit.to_crumble_url`

.github/workflows/ci.yml, glue/sample/src/sinter/_decoding/_decoding_all_built_in_decoders.py, glue/sample/src/sinter/_decoding/_decoding_mwpf.py, glue/sample/src/sinter/_decoding/_decoding_test.py
(This PR is just a merge-conflict-resolved version of https://github.com/quantumlib/Stim/pull/815)
> This is a simple adaptation of the `mwpf' python package to sinter. Just copied the `_decoding_fusion.py` and modify it accordingly to let the decoder consider hyperedges. Tested using the `getting_started.ipynb` and they run decoding without a problem.
> I haven't added any test cases for this, since I didn't find a test case for `fusion_blossom` decoder as well. Please let me know where should I put a basic test case for the new decoders!
The existing unit tests automatically iterate over the defined decoders and run them through some basic sanity checks.
Authored by @yuewuo
=> Add `"hypergraph_union_find"` and `"mw_parity_factor"` decoders to sinter

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc
Fixes https://github.com/quantumlib/Stim/issues/691
=> Fix docstring typo in `to_qasm`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/stabilizers/tableau.pybind.cc, src/stim/stabilizers/tableau_pybind_test.py, src/stim/util_top/circuit_vs_amplitudes.cc, src/stim/util_top/circuit_vs_amplitudes.h, src/stim/util_top/circuit_vs_amplitudes.test.cc
Just taking a stab at fixing https://github.com/quantumlib/Stim/issues/638. Note, I don't fully understand how Tableau should work but I wrote the tests based on the examples, so I think this should be correct.
- Adds normalization code by scaling each amplitude by the square root of the inverse of the state vector norm
- Adds tests to match the examples from `from_state_vector` including an unnormalized version
=> Remove the constraint that stim.Tableau.from_state_vector inputs must be normalized

doc/gates.md, src/stim/circuit/circuit_pybind_test.py, src/stim/cmd/command_help.cc, src/stim/gates/gate_data_pauli_product.cc, src/stim/gates/gates.cc, src/stim/gates/gates.h, src/stim/gates/gates.pybind.cc, src/stim/gates/gates.test.cc, src/stim/gates/gates_test.py, src/stim/py/stim_pybind_test.py, src/stim/simulators/error_analyzer.test.cc, src/stim/simulators/frame_simulator.test.cc, src/stim/simulators/graph_simulator.test.cc, src/stim/simulators/sparse_rev_frame_tracker.test.cc, src/stim/simulators/tableau_simulator.test.cc, src/stim/stabilizers/pauli_string_ref.test.cc, src/stim/stabilizers/tableau.test.cc, src/stim/util_top/stabilizers_vs_amplitudes.test.cc
- Fix `SPP` not being classified as a unitary gate
- Fix `SPP_DAG` not being classified as a unitary gate
- Fix some code/tests assuming a gate being unitary implies it has a non-target-dependent unitary matrix
Fixes https://github.com/quantumlib/Stim/issues/846
=> Fix `stim.Circuit.to_tableau` ignoring `SPP` and `SPP_DAG`

glue/sample/src/sinter/_decoding/_decoding_fusion_blossom.py, glue/sample/src/sinter/_decoding/_decoding_mwpf.py
The packed obs predictions should be of shape `(num_shots, (self.num_obs + 7) // 8)` instead of `(num_shots, self.num_obs)`, which results in error `ValueError: predictions.shape[1] > actual_obs.shape[1] + 1` when simulating codes with multiple logical observables.
=> Fix observable predictions shape in sinter's MWPF and FussionBlossom decoder

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/cirq/stimcirq/_cirq_to_stim.py, glue/cirq/stimcirq/_cirq_to_stim_test.py, glue/cirq/stimcirq/_cx_swap_gate.py, glue/cirq/stimcirq/_cz_swap_gate.py, glue/cirq/stimcirq/_det_annotation.py, glue/cirq/stimcirq/_measure_and_or_reset_gate.py, glue/cirq/stimcirq/_obs_annotation.py, glue/cirq/stimcirq/_shift_coords_annotation.py, glue/cirq/stimcirq/_stim_to_cirq.py, glue/cirq/stimcirq/_stim_to_cirq_test.py, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/util_top/export_crumble_url.test.cc
- Add `tag: str = ""` to `stim.Circuit.append`
- Stim tags now become string tags on cirq circuit operations
- A string tag on a cirq operation will turn into a stim tag by default if there is exactly one such string tag
- Add optional  `tag_func` argument to `stimcirq.cirq_circuit_to_stim_circuit`
Some inspiration from https://github.com/quantumlib/Stim/pull/862
=> Add stimcirq tag conversions

dev/util_gen_stub_file.py, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_repeat_block.pybind.cc, src/stim/circuit/gate_target.pybind.cc, src/stim/py/numpy.pybind.cc, src/stim/search/sat/wcnf.cc, src/stim/search/sat/wcnf.h, src/stim/simulators/frame_simulator.pybind.cc, src/stim/simulators/frame_simulator_pybind_test.py, src/stim/simulators/matched_error.pybind.cc, src/stim/simulators/tableau_simulator.pybind.cc
- Add `stim.FlipSimulator.generate_bernoulli_samples`
- Add `stim.FlipSimulator.to_numpy`
- Fix bit packed numpy outputs not masking off bits beyond a non-multiple-of-8 result count
- Fix remaining "doc doesn't include example" warnings from regen_docs script
Fixes https://github.com/quantumlib/Stim/issues/875
Fixes https://github.com/quantumlib/Stim/issues/877
=> Add `stim.FlipSimulator.{to_numpy,generate_bernoulli_samples}`

dev/util_gen_stub_file.py, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/simulators/tableau_simulator.pybind.cc
- Add a check to the signature override code that verifies the name isn't changed
Fixes https://github.com/quantumlib/Stim/issues/878
=> Fix typo in `stim.TableauSimulator.z_error`'s signature override

.github/workflows/ci.yml
Google's terms for allowing the use of GitHub Actions on Google-owned repositories requires that third-party actions be referenced using a specific commit, not a tagged release or a branch name. They also recommend that GitHub-hosted runners be referenced by fixed versions and not "-latest". (Internal doc link: go/github-actions#actions)
The SHAs for GitHub Actions in this commit were obtained using [frizbee](https://github.com/stacklok/frizbee). The runner versions equivalent to the "-latest" runners are based on the table at https://github.com/actions/runner-images
=> Pin versions of 3rd-party actions and GitHub runners

.github/SECURITY.md, CODE_OF_CONDUCT.md, SUPPORT.md
This adds a security policy, code of conduct, and general support info, per GitHub and Google best practices.
=> Add some common repository files for GitHub best practices

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit.test.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/dem/detector_error_model.cc, src/stim/dem/detector_error_model.h, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model_pybind_test.py
- Add `stim.Circuit.without_tags`
- Add `stim.CircuitDetectorErrorModel.without_tags`
Fixes https://github.com/quantumlib/Stim/issues/884
=> Add `stim.{Circuit,DetectorErrorModel}.without_tags`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/dem/detector_error_model.pybind.cc
Fixes https://github.com/quantumlib/Stim/issues/851
=> Fix `*.from_file` examples opening a file then not using it

src/stim/stabilizers/tableau_iter.inl, src/stim/stabilizers/tableau_pybind_test.py
- It now returns an iterator that yields the empty tableau then stops
Fixes https://github.com/quantumlib/Stim/issues/859
=> Fix `stim.Tableau.iter_all(0)` segfaulting

CITATION.cff
This removes a redundant entry for the GitHub repo in the "identifiers" section -- one that had the wrong URL anyway.
It also adds some explanatory comments to help everyone figure out why there seem to 2 similar overall blocks in here.
=> Remove incorrect entry in "identifiers" in CITATION.cff

.github/workflows/ci.yml
This is a LSC run by http://go/ghss to upgrade all depreacated ubuntu-20.04 runners to ubuntu-24.04.
On April 1, 2025, GitHub will stop supporting ubuntu-20.04 runners and workflows configured with this label will cease to run.  This PR is an attempt to save you work by doing the upgrade for you.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it and deal with the problem yourselves.
More context and feedback: http://b/406537467
=> Update runners to ubuntu-24.04 from deprecated ubuntu-20.04 label

.github/workflows/ci.yml
This adds steps to the test_sinter job to create a pip constraints
file that constrains the version of cmake to be less than 4.0.0, to
work around the failures in CI due to issue #920.
=> Temporary workaround for issue #920

doc/sinter_api.md, glue/sample/src/sinter/_probability_util.py
Make consistent with numpy v2 instead of numpy v1 (triggered by pymatching now supporting numpy v2)
Fixes https://github.com/quantumlib/Stim/issues/924
=> Fix sinter doctests

doc/sinter_api.md, glue/sample/src/sinter/_collection/_collection_worker_test.py, glue/sample/src/sinter/_decoding/_decoding_decoder_class.py, glue/sample/src/sinter/_decoding/_decoding_test.py, glue/sample/src/sinter/_decoding/_stim_then_decode_sampler.py
- The class `sinter.Decoder` now implements `decode_via_files` by calling `compile_decoder_for_dem`
- Child classes now must implement at least one of `decode_via_files` or `compile_decoder_for_dem`
- Sinter's internal fallback to `sinter.Decoder.decode_via_files` now only occurs if `sinter.Decoder.compile_decoder_for_dem` raises a `NotImplementedError` (it no longer happens if a `ValueError` was raised).
- Also, make one of the multiprocessing unit tests less flaky by waiting up to a second for messages to arrive
Fixes https://github.com/quantumlib/Stim/issues/923
=> Make `sinter.Decoder.decode_via_files` fallback to `sinter.Decoder.compile_decoder_for_dem`

src/stim/simulators/frame_simulator.pybind.cc, src/stim/simulators/frame_simulator_pybind_test.py
- Casting to unsigned before checking if non-negative resulted in negative values always looking too large
Fixes https://github.com/quantumlib/Stim/issues/926
=> Fix overly strict bounds checking for negative indices in FlipSimulator

src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.test.cc, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/simulators/sparse_rev_frame_tracker.h, src/stim/util_top/circuit_to_detecting_regions.cc, src/stim/util_top/circuit_to_detecting_regions_test.py
- Also fix detslice diagrams not drawing these anticommutations
Fixes https://github.com/quantumlib/Stim/issues/922
=> Fix `stim.Circuit.detecting_regions` not failing on anticommutations at start of circuit

doc/python_api_reference_vDev.md, doc/stim.pyi, file_lists/source_files_no_main, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit2.pybind.cc, src/stim/mem/simd_bit_table.h, src/stim/mem/span_ref.h, src/stim/simulators/frame_simulator.inl, src/stim/simulators/frame_simulator.test.cc, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/stabilizers/flow.h, src/stim/stabilizers/flow.inl, src/stim/stabilizers/flow.pybind.cc, src/stim/stabilizers/flow.test.cc, src/stim/stabilizers/flow_pybind_test.py, src/stim/util_bot/probability_util.cc, src/stim/util_top/circuit_inverse_qec.h, src/stim/util_top/has_flow.cc, src/stim/util_top/has_flow.h, src/stim/util_top/has_flow.inl, src/stim/util_top/has_flow.test.cc
- Fix pauli term `OBSERVABLE_INCLUDE` instructions having X/Z sensitivity inverted when sampling detection events
- Add field `stim.Flow.included_observables`
- Add argument `stim.Flow(..., included_observables=None)`
- Improve documentation of `stim.Circuit.solve_flow_measurements`
- `stim.Flow` now xor-sorts its measurements (and included_observables)
The 'included observables' of a flow say which `OBSERVABLE_INCLUDE` instructions to implicitly add into the flow. This allows flows to make statements about observables.
Fixes https://github.com/quantumlib/Stim/issues/940
=> Add `stim.Flow(included_observables=...)` and fix X/Z inversion when sampling observables with free-floating Pauli terms

doc/gates.md, doc/python_api_reference_vDev.md, doc/sinter_api.md, doc/stim.pyi, file_lists/source_files_no_main, file_lists/test_files, glue/python/src/stim/__init__.pyi, src/stim.h, src/stim/cmd/command_help.cc, src/stim/stabilizers/flow.h, src/stim/stabilizers/flow.inl, src/stim/stabilizers/flow.pybind.cc, src/stim/stabilizers/flow_pybind_test.py, src/stim/stabilizers/pauli_string_ref.inl, src/stim/util_top/mbqc_decomposition.cc, src/stim/util_top/mbqc_decomposition.h, src/stim/util_top/mbqc_decomposition.test.cc
- Fix `stim.Flow.__init__` not xor-sorting measurements/observables
- Add `stim.Flow.__mul__`
=> Add MBQC decompositions to the gates documentation

glue/sample/src/sinter/_collection/_collection_manager.py, glue/sample/src/sinter/_collection/_collection_test.py, glue/sample/src/sinter/_collection/_sampler_ramp_throttled_test.py
When `max_batch_size` is passed to `sinter.collect` it gets passed to the `CollectionOptions` for the `CollectionManager` but then in `CollectionManager.start_workers` it is not passed on to the `RampThrottledSampler` instead `max_batch_shots` is hardcoded to 1024 [here](https://github.com/quantumlib/Stim/blob/9156ab6c97c4f27be1160cd8b6aafb35f7677e57/glue/sample/src/sinter/_collection/_collection_manager.py#L140).  I have seen some small improvements in runtime when I can go for larger batches. 
This PR passes `max_batch_size` to `RampThrottledSampler.max_batch_shots` and adds some test coverage.
=> connect max_batch_size from CollectionManager to worker RampThrottledSampler

CONTRIBUTING.md
This addresses the incorrect instructions reported in issue #944. The instructions now reference `doc/developer_documentation.md`.
=> Replace incorrect development instructions

package-lock.json, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/measurements_to_detection_events_test.py
Add serialization capabilities to CompiledMeasurementsToDetectionEventsConverter.
=> Add pickling support to `stim.CompiledMeasurementsToDetectionEventsConverter`

glue/lattice_surgery/lassynth/translators/gltf_generator.py
Initialize the `s_bound` variable if `lasre` does not have correlation surface information. The use case is when we only want to make use of the lasre solution format for visualization, etc.
=> Fix uninitialized var case in LaSsynth

.github/workflows/ci.yml
Enable the Python 3.13 build, such that there is a wheel built for the next release on PyPI
This works now (as `numpy` wheels have been uploaded since April 2024). Tested here: https://github.com/guenp/Stim/actions/runs/17592185854
=> release: Enable Python 3.13 build for Windows
