quantumlib/Stim

.github/workflows/ci.yml, .gitignore, README.md, glue/cirq/setup.py, glue/python/README.md, setup.py
- Bump version to 1.0.dev
- Add python-specific README for stim pip package
- Fix setup.py not including READMEs
=> Polish packaging

glue/cirq/setup.py, glue/python/README.md, glue/python/generate_api_reference.py, setup.py, src/circuit/circuit.pybind.cc, src/py/stim.pybind.cc, src/py/stim_pybind_test.py
- Fix `stim.__version__` saying "VERSION_INFO" instead of the version
- Fix some unnamed pybind11 arguments
- Add generate_api_reference.py dev helper script
=> Polishing in preparation for v1.1 release

src/circuit/circuit.pybind.cc, src/py/compiled_measurement_sampler.pybind.cc, src/simulators/tableau_simulator.pybind.cc, src/stabilizers/pauli_string.pybind.cc, src/stabilizers/tableau.pybind.cc
- Triple-quotes were triggering https://youtrack.jetbrains.com/issue/PY-47605
- Also polish a few more docstrings (add examples, arg names)
=> Work around pycharm autocomplete bug caused by """ in __doc__

src/simulators/error_fuser.test.cc
- Failed at some optimization levels
=> Fix overly precise unit test

setup.py, src/probability_util.cc
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94087
Fixes https://github.com/quantumlib/Stim/issues/26
=> Workaroud std::random_device bug

src/circuit/circuit.cc, src/circuit/circuit.h, src/circuit/circuit.pybind.cc, src/circuit/circuit_gate_target.pybind.cc, src/circuit/circuit_gate_target.pybind.h, src/circuit/circuit_gate_target_pybind_test.py, src/circuit/circuit_instruction.pybind.cc, src/circuit/circuit_instruction.pybind.h, src/circuit/circuit_instruction_pybind_test.py, src/circuit/circuit_pybind_test.py, src/circuit/circuit_repeat_block.pybind.cc, src/circuit/circuit_repeat_block.pybind.h, src/circuit/circuit_repeat_block_test.py
- Add `stim.CircuitRepeatBlock`
- Add `stim.CircuitInstruction`
- Add `stim.GateTarget`
- Add `stim.Circuit.__getitem__`
- Add `stim.Circuit.__len__`
=> Add introspection of Circuit instructions

doc/file_format_dem_detector_error_model.md, doc/file_format_stim_circuit.md
- Fixes https://github.com/quantumlib/Stim/issues/75
- Fixes https://github.com/quantumlib/Stim/issues/64
=> Polish file format documentation

src/circuit/circuit.cc, src/circuit/circuit.h, src/circuit/circuit.test.cc, src/main_helper.test.cc, src/simulators/error_analyzer.cc, src/simulators/frame_simulator.test.cc
- Add Operation::count_measurement_results
=> Fix miscounting measurements when using MPP

src/io/measure_record_writer.cc, src/io/measure_record_writer.h, src/io/measure_record_writer.test.cc
=> Fix DETS format writer's handling of multiple records

GATES.md, doc/gates.md, src/circuit/gate_data_period_4.cc
* Correct "principle square root" to "principal square root"
* Correct the dagger gate docs to read "Adjoint of the principal square root"
=> Documentation corrections

src/stim/io/measure_record_reader.cc, src/stim/io/measure_record_reader.h, src/stim/io/measure_record_reader.test.cc
- And remove current_result_type from protocol
=> Fix read_bits_into_bytes stopping at result-type boundaries

src/stim/dem/detector_error_model.cc
=> Explicitly include <limits> in detector_error_model.cc

src/stim/io/measure_record_reader.cc, src/stim/io/measure_record_reader.h, src/stim/simulators/measurements_to_detection_events.cc, src/stim/simulators/measurements_to_detection_events.test.cc
- Also fix 01 reader incorrectly complaining about correctly empty shots
=> Fix m2d going into an infinite loop for empty circuit b8 data

src/stim/circuit/circuit_pybind_test.py, src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.h, src/stim/simulators/measurements_to_detection_events.cc
Fixes https://github.com/quantumlib/Stim/issues/117
=> Fix MPP anticommute message not saying MPP

glue/zx/README.md
- Note that it's not a published package so has to be installed from source
- Fix one of the examples having the wrong output
- Add s state distillation as an example
=> Clarify stimzx readme

glue/cirq/stimcirq/_cirq_to_stim.py, glue/cirq/stimcirq/_cirq_to_stim_test.py
Fixes https://github.com/quantumlib/Stim/issues/231
=> Handle identity in DensePauliString

glue/sample/src/sinter/collection.py, src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.test.cc
- Fix sinter progress message mentioning one fewer processes than requested
- Fix loop folding incorrectly folding loops with observables including measurements from only the last few iterations
=> Fix a loop folding bug

glue/sample/src/sinter/collection_work_manager.py, glue/sample/src/sinter/decoding.py, glue/sample/src/sinter/decoding_internal.py, glue/sample/src/sinter/decoding_pymatching.py, glue/sample/src/sinter/decoding_test.py, glue/sample/src/sinter/plotting.py, glue/sample/src/sinter/predict.py, glue/sample/src/sinter/predict_test.py
- Refactor the decoding methods to take file paths instead of numpy arrays
- Do streaming of data when it needs to be loaded
- Fix plotting methods not converting x_func output to a float
=> Make sinter work with data on disk instead of in memory

glue/sample/src/sinter/main_test.py, glue/sample/src/sinter/plotting.py, glue/sample/src/sinter/plotting_test.py, glue/sample/src/sinter/probability_util.py, glue/sample/src/sinter/probability_util_test.py
- Fix a bug in sinter.better_sorted_str_terms
=> Improve precision of sinter.shot_error_rate_to_piece_error_rate

CMakeLists.txt, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/generate_stub_file.py, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/dem/detector_error_model.pybind.cc, src/stim/dem/detector_error_model_pybind_test.py, src/stim/io/raii_file.cc, src/stim/io/raii_file.h, src/stim/io/read_write.pybind.cc, src/stim/py/compiled_detector_sampler.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.cc, src/stim/simulators/measurements_to_detection_events.pybind.h
Fixes https://github.com/quantumlib/Stim/issues/262
=> Add `stim.{Circuit,DetectorErrorModel}.{to_file,from_file}`

glue/sample/src/sinter/_main_plot.py
- Aso fix a "-" vs "--" typo in one of the help messages
=> Add "--miny" option to sinter plot

glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_test.py
- Also show major grid and minor grid in the plots
- Also fix changing log-vs-not-log after setting ylim / ticks, which causes problems
=> Add `--title` option to sinter plot 

src/stim/mem/simd_bit_table.h, src/stim/mem/simd_bit_table.inl
Small refactor of transpose code
=> Extract helper method simd_bit_table::get_index_of_bitword

src/stim/simulators/error_analyzer.cc, src/stim/simulators/error_analyzer.test.cc
=> Fix the '15 detector' limit on decomposing also applying when not decomposing errors

glue/sample/src/sinter/_plotting.py
When using sinter's convenient plotting functions, I found myself doing this a lot:
```
plotted_stats = [
stat
for stat in stats
if (stat.json_metadata['b'] == 'z' and stat.json_metadata['type'] == tl)
]
sinter.plot_error_rate(
ax=ax,
stats=plotted_stats,
group_func=lambda stat: f"p={stat.json_metadata['p']}",
x_func=lambda stat: stat.json_metadata['d'],
)
```
and I thought to myself, why not have sinter do that for me too?
This is a minimally invasive attempt to put the `filter_func` behavior from the command line api into the python functions.
It currently doesn't disturb the way the cmd `filter_func` is used, which is external to the plotting calls and reused between calls to `plot_error_rates` and `plot_discard_rates`. We could just hand `filter_func` down to both functions, at the …
=> Give the people filter_func

src/stim/simulators/dem_sampler.cc, src/stim/simulators/dem_sampler.h, src/stim/simulators/dem_sampler.pybind.cc, src/stim/simulators/dem_sampler_pybind_test.py
:scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: …
=> Fix stim.DemSampler.sample only filling in 1024 shots maximum

dev/regen_file_lists.sh, doc/usage_command_line.md, file_lists/source_files_no_main, file_lists/test_files, src/stim.h, src/stim/cmd/command_diagram.cc, src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.h, src/stim/diagram/detector_slice/detector_slice_set.test.cc
- Auto-generate the stim.h header file when regenerating file lists
=> Add detector slice diagrams

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/javascript/circuit.js.cc, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit.perf.cc, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit.test.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/circuit/gate_data.test.cc, src/stim/diagram/detector_slice/detector_slice_set.test.cc, src/stim/gen/circuit_gen_params.cc, src/stim/gen/gen_color_code.cc, src/stim/gen/gen_rep_code.cc, src/stim/gen/gen_surface_code.cc, src/stim/main_namespaced.perf.cc, src/stim/mem/simd_word.h, src/stim/simulators/frame_simulator.test.cc, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/stabilizers/conversions.cc
- Also renamed some of the C++ circuit append methods
Fixes https://github.com/quantumlib/Stim/issues/401
=> Add `stim.Circuit.inverse`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/simulators/tableau_simulator.cc, src/stim/simulators/tableau_simulator.h, src/stim/simulators/tableau_simulator.pybind.cc, src/stim/simulators/tableau_simulator.test.cc, src/stim/simulators/tableau_simulator_pybind_test.py
Fixes https://github.com/quantumlib/Stim/issues/396
=> Add stim.TableauSimulator.measure_pauli_string

glue/cirq/stimcirq/_stim_sampler.py, glue/cirq/stimcirq/_stim_sampler_test.py
This modifies `StimSampler` to allow it to handle cirq circuits with repeated measurements. Note that I've left `cirq_circuit_to_stim_data` alone, since it was already returning repeated keys in a list, these just needed to be aggregated to find all indices that should be extracted from the stim samples for each key. It would also be possible to do this aggregation in `cirq_circuit_to_stim_data` and return the information about measurement keys in aggregated form from there. Let me know if you'd prefer that.
On a related note, the current conversion from stim circuits to cirq circuits does not take advantage of repeated keys, but instead uses a separate key for every measurement. It would be nice to change this to take advantage of repeated key support, since it makes the result data more …
=> Support repeated keys in StimSampler

src/stim/diagram/detector_slice/detector_slice_set.cc, src/stim/diagram/detector_slice/detector_slice_set.h, src/stim/diagram/detector_slice/detector_slice_set.test.cc, src/stim/test_util.test.cc, testdata/colinear_detector_slice.svg, testdata/rotated_memory_z_detector_slice.svg, testdata/surface_code_time_detector_slice.svg
Fixes https://github.com/quantumlib/Stim/issues/423
=> Disambiguate colinear detector slice vertices using curvature

.github/workflows/ci.yml, dev/regen_docs.sh, dev/regen_file_lists.sh, glue/python/src/stim/__init__.py, setup.py, src/stim/mem/monotonic_buffer.h
- This is a precaution because presumably other people have environments like colab's. Ideally I would understand why the crash is happening, but currently I don't.
- Make various tweaks and improvements to CI
Related issue: https://github.com/quantumlib/Stim/issues/432
=> Disable avx2 python extension due to colab crash

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit_instruction.pybind.cc, src/stim/circuit/circuit_instruction.pybind.h, src/stim/simulators/frame_simulator.test.cc, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/pauli_string.test.cc, src/stim/stabilizers/pauli_string_pybind_test.py, src/stim/stabilizers/pauli_string_ref.cc, src/stim/stabilizers/pauli_string_ref.h, src/stim/stabilizers/tableau.cc, src/stim/stabilizers/tableau.h, src/stim/stabilizers/tableau.test.cc
Fixes https://github.com/quantumlib/Stim/issues/308
=> Add `stim.PauliString.{before,after}`

BUILD, setup.py, src/stim/benchmark_main.perf.cc, src/stim/diagram/timeline/timeline_ascii_drawer.cc, src/stim/gen/circuit_gen_params.cc, src/stim/gen/circuit_gen_params.h, src/stim/gen/gen_color_code.cc, src/stim/gen/gen_rep_code.cc, src/stim/gen/gen_surface_code.cc, src/stim/mem/simd_bits.h, src/stim/mem/simd_bits.inl, src/stim/mem/simd_bits_range_ref.h, src/stim/mem/simd_bits_range_ref.inl, src/stim/stabilizers/pauli_string.cc, src/stim/stabilizers/pauli_string.h
- Port over some changes needed for eventual C++20 compatibility
- Enable compiler optimizations on Windows
=> Increase OS and future C++ version compatibility

doc/gates.md, src/stim/circuit/gate_data_controlled.cc, src/stim/circuit/gate_data_pp.cc, src/stim/circuit/gate_data_swaps.cc
=> Reduce number of two-qubit gates in decompositions

doc/gates.md, doc/python_api_reference_vDev.md, doc/stim.pyi, doc/usage_command_line.md, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/circuit/gate_data_controlled.cc, src/stim/cmd/command_diagram.cc, src/stim/diagram/detector_slice/detector_slice_set.cc
- Note the ability to classically control gates in the gates reference
- Fix some documentation typos
- Fix a hang in detslice-with-ops-svg when not specifying ticks
Fixes https://github.com/quantumlib/Stim/issues/496
Fixes https://github.com/quantumlib/Stim/issues/502
Fixes https://github.com/quantumlib/Stim/issues/504 
Fixes https://github.com/quantumlib/Stim/issues/511 
Fixes https://github.com/quantumlib/Stim/issues/512
=> Variety pack of issue fixes

src/stim/cmd/command_explain_errors.test.cc, src/stim/cmd/command_m2d.test.cc, src/stim/simulators/error_matcher.cc, src/stim/simulators/measurements_to_detection_events.cc, src/stim/test_util.test.cc, src/stim/test_util.test.h
Original mystery was reported by @AlexBourassa
=> Fix m2d failing when --obs_out internally crosses a simd boundary

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc
=> Fix missing paren in "as needed ..."

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py
Fixes https://github.com/quantumlib/Stim/issues/540
=> Add `stim.Circuit.num_ticks`

glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_plot_test.py
Fixes https://github.com/quantumlib/Stim/issues/542
=> Fix some `sinter plot` crashes on degenerate data

dev/util_gen_stub_file.py, doc/sinter_api.md, doc/sinter_command_line.md, glue/sample/src/sinter/_collection.py, glue/sample/src/sinter/_collection_tracker_for_single_task.py, glue/sample/src/sinter/_collection_work_manager.py, glue/sample/src/sinter/_csv_out.py, glue/sample/src/sinter/_json_type.py, glue/sample/src/sinter/_main_collect.py, glue/sample/src/sinter/_main_collect_test.py, glue/sample/src/sinter/_main_combine.py, glue/sample/src/sinter/_task.py, glue/sample/src/sinter/_task_stats.py, glue/sample/src/sinter/_worker.py
- Add `sinter combine --strip_custom_counts`
- Add `sinter collect --custom_error_count_key`
- Add `sinter collect --allowed_cpu_affinity_ids`
- Remove `sinter._json_type` as it was causing doc problems
- Do some fixups to sinter's command line documentation
Fixes https://github.com/quantumlib/Stim/issues/550
=> Various sinter fixes and additions

doc/sinter_api.md, doc/sinter_command_line.md, glue/sample/src/sinter/_collection.py, glue/sample/src/sinter/_main_collect.py, glue/sample/src/sinter/_main_collect_test.py, glue/sample/src/sinter/_main_plot.py, glue/sample/src/sinter/_main_plot_test.py, glue/sample/src/sinter/_plotting.py, src/stim.h, src/stim/simulators/force_streaming.h
- Add `sinter plot --line_fits`
- Add `sinter plot --xmax`
- Add `sinter plot --xmin`
- Add `sinter collect --processes=auto`
- Say number of workers when starting collection
=> Add some convenience features to sinter

src/stim/circuit/circuit_pybind_test.py, src/stim/dem/detector_error_model_pybind_test.py, src/stim/search/graphlike/algo.cc, src/stim/search/hyper/algo.cc
=> New error messages in search algos

src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/circuit/circuit_instruction.h, src/stim/circuit/gate_data.h, src/stim/diagram/ascii_diagram.h, src/stim/diagram/base64.h, src/stim/diagram/gate_data_svg.h, src/stim/mem/simd_word.h, src/stim/search/hyper/algo.cc, src/stim/search/hyper/algo.h, src/stim/simulators/frame_simulator.h, src/stim/simulators/frame_simulator.pybind.cc
Fixes https://github.com/quantumlib/Stim/issues/580
=> Fix gcc13 build failures

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/gate_data.h, src/stim/circuit/gate_data.pybind.cc, src/stim/circuit/gate_data_test.py, src/stim/cmd/command_diagram.pybind.cc, src/stim/main_namespaced.test.h
Fixes https://github.com/quantumlib/Stim/issues/621
=> Add `stim.GateData.{__eq__,__ne__,__repr__,__init__,__str__}`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/stabilizers/pauli_string.pybind.cc, src/stim/stabilizers/pauli_string.test.cc, src/stim/stabilizers/pauli_string_ref.h, src/stim/stabilizers/pauli_string_ref.inl
Fixes https://github.com/quantumlib/Stim/issues/626
=> Add `stim.PauliString.weight`

.github/workflows/ci.yml, BUILD, CMakeLists.txt, doc/developer_documentation.md, glue/javascript/build_wasm.sh, setup.py, src/stim/mem/bitword_128_sse.h, src/stim/mem/bitword_256_avx.h, src/stim/mem/bitword_64.h, src/stim/mem/simd_bits_range_ref.inl, src/stim/mem/simd_util.h, src/stim/mem/simd_util.test.cc, src/stim/probability_util.test.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/vector_simulator.h, src/stim/stabilizers/pauli_string.pybind.cc
- Replace bit twiddly `popcount64` with `std::popcount`
=> Bump targeted C++ standard to C++20

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/circuit/gate_data.test.cc, src/stim/circuit/stabilizer_flow.h, src/stim/circuit/stabilizer_flow.inl, src/stim/circuit/stabilizer_flow.test.cc, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/simulators/sparse_rev_frame_tracker.h, src/stim/simulators/sparse_rev_frame_tracker.test.cc, src/stim/stabilizers/tableau.pybind.cc
Fixes https://github.com/quantumlib/Stim/issues/645
=> Add `stim.Circuit.has_flow`

src/stim/stabilizers/pauli_string.h, src/stim/stabilizers/pauli_string.inl, src/stim/stabilizers/pauli_string.test.cc, src/stim/stabilizers/pauli_string_ref.h, src/stim/stabilizers/pauli_string_ref.inl, src/stim/stabilizers/pauli_string_ref.test.cc
- Add `stim::PauliString::safe_accumulate_pauli_term`
- Add `stim::PauliStringRef::has_no_pauli_terms`
- Add `stim::PauliStringRef::intersects`
=> Add some C++ pauli string utility methods

doc/gates.md, doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py, src/stim/circuit/export_qasm.cc, src/stim/circuit/export_qasm.test.cc, src/stim/circuit/export_qasm_pybind_test.py, src/stim/circuit/gate_decomposition.cc, src/stim/circuit/gate_decomposition.h, src/stim/circuit/gate_decomposition.test.cc, src/stim/circuit/gate_target.cc, src/stim/circuit/gate_target.h, src/stim/circuit/gate_target.test.cc, src/stim/cmd/command_help.cc, src/stim/cmd/command_help.h, src/stim/diagram/circuit_timeline_helper.cc, src/stim/gates/gate_data_annotations.cc, src/stim/gates/gates.test.cc, src/stim/simulators/error_analyzer.cc, src/stim/simulators/frame_simulator.inl, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/simulators/tableau_simulator.inl, src/stim/simulators/tableau_simulator.test.cc
- And allow `MPAD` to take a noise argument
=> Add `stim.Circuit.decomposed`

file_lists/source_files_no_main, src/stim/circuit/circuit.cc, src/stim/circuit/circuit.h, src/stim/simulators/sparse_rev_frame_tracker.cc, src/stim/simulators/sparse_rev_frame_tracker.h, src/stim/simulators/transform_without_feedback.test.cc, src/stim/util_top/circuit_inverse_qec.cc, src/stim/util_top/circuit_inverse_qec.h, src/stim/util_top/circuit_inverse_qec.inl, src/stim/util_top/circuit_inverse_qec.test.cc, src/stim/util_top/circuit_inverse_qec_test.py
- Also, refactor the C++ code to be a class with methods instead of one big function
=> Fix flows past end of circuit segfaulting `time_reversed_for_flows`

doc/python_api_reference_vDev.md, doc/stim.pyi, file_lists/test_files, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit_instruction.h, src/stim/circuit/circuit_instruction.pybind.cc, src/stim/circuit/circuit_instruction.pybind.h, src/stim/circuit/circuit_instruction.test.cc, src/stim/circuit/circuit_instruction_pybind_test.py, src/stim/circuit/gate_target.cc, src/stim/circuit/gate_target.pybind.cc, src/stim/dem/dem_instruction.h, src/stim/dem/dem_instruction.test.cc, src/stim/dem/detector_error_model_instruction.pybind.cc, src/stim/dem/detector_error_model_instruction.pybind.h, src/stim/dem/detector_error_model_instruction_pybind_test.py, src/stim/diagram/graph/match_graph_3d_drawer.h, src/stim/gates/gate_data_annotations.cc, src/stim/simulators/matched_error.pybind.cc
Fixes https://github.com/quantumlib/Stim/issues/811
=> Add `stim.{CircuitInstruction,DemInstruction}.target_groups`

doc/python_api_reference_vDev.md, doc/stim.pyi, glue/python/src/stim/__init__.pyi, src/stim/circuit/circuit.pybind.cc, src/stim/circuit/circuit_pybind_test.py
Fixes https://github.com/quantumlib/Stim/issues/841
=> Add `stim.Circuit.reference_detector_and_observable_signs`

doc/circuit_data_references.md
Fixes https://github.com/quantumlib/Stim/issues/861
=> Add some more circuit data references

.github/workflows/ci.yml, glue/cirq/stimcirq/_cirq_to_stim_test.py
Fixes https://github.com/quantumlib/Stim/issues/882
=> Prebuild wheels for python 3.13
